### ISSUE TITLE
Load FreeTFT Account

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/tft-stellar#103]
We need some XLM to cover trustline & exchange costs for the FreeTFT:

XLM Address:
GC4P6SOCUJ4TKBNEF4CBO46QDHNZG3GPUSHPHWUBR6TSL4KS6KSQC4XK

**Comment by robvanmieghem** [comment]
account activated, let me know when the trustline is there and how many Freetft you need

**Comment by VonSub** [comment]
trustline created, let's shoot for 250 devs so 250000 FreeTFT

**Comment by robvanmieghem** [comment]
https://stellar.expert/explorer/public/tx/126247647383486464#126247647383486465
