### ISSUE TITLE
modify the conversion service to tfta

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#107]
tfta should be issued but according to the spec:
>time locked TFT on the rivine chain become time locked TFTA if the locktime expires before 2021. I the locktime expires after 2020, they become time locked TFT on the Stellar blockchain

**Comment by DylanVerstraete** [comment]
> I the locktime expires after 2020, they become time locked TFT on the Stellar blockchain

@robvanmieghem don't you mean expires after 2022 ?

**Comment by gmachtel** [comment]
No, tipping point is 1/1/2021 0h00. TFchain-TFT that aren't locked or have locktime that expires in 2020 should be converted to Stellar-TFTA. If locked until 2021 or later, conversion to Stellar-TFT.
