### ISSUE TITLE
Conversion service doesn't work with locked balances

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldfoundation/tft-stellar#118]
I created a TFChain account and putted locked tokens on it. The tokens had an unlockdate in 2020 and 2021. 
Migrate tokens did return an error and wasn't able to convert.
![image](https://user-images.githubusercontent.com/17977313/80609450-5cec1980-8a38-11ea-8cee-9fe4cbfc8ccb.png)

The migrate tokens did work for an account without locked

**Comment by DylanVerstraete** [comment]
Fixed in https://github.com/threefoldtech/jumpscaleX_libs/commit/ac39511e3f91a3a0624caa668e9fb2d3cfa7f7bd

**Comment by robvanmieghem** [comment]
reopened since it has not been deployed yet

**Comment by robvanmieghem** [comment]
deployed

**Comment by tobiaschielens** [comment]
It is working on my side, this can be closed
