### ISSUE TITLE
Payment amount is getting rounded in service

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldfoundation/tft-stellar#123]
When sending specific amounts to the fund_transaction service the payment amount is getting rounded. This example covers an amount of 1876876875 tokens on testnet.
 
The xdr before sending it to the fund_transaction service:
"AAAAAEwscuR35c8eIYmqX31lHTco9lzgOQJJrcySmjJHY54WAAAAAAAADPkAAAACAAAAAQAAAAAAAAAAAAAAAF6xghsAAAABAAAAAAAAAAEAAAABAAAAAEwscuR35c8eIYmqX31lHTco9lzgOQJJrcySmjJHY54WAAAAAQAAAACFcODMIMVtnNLkRj7rTf79Zp9oKIJ36fQ5XK5nFtpBeAAAAAFURlRBAAAAAHvQcjHhtMQ6KZwBxfikbmn1ct8EzY9h09Ctz7Oyzg2FAEKuGII3F4AAAAAAAAAAAA"

The xdr when receiving the transaction back from the service:
"AAAAAFao6qzQcUlmzyG/xxo0cGvdSTg9TvFPLvmOFSGn2FUyAAAAyAAACzsAAAASAAAAAQAAAAAAAAAAAAAAAF6ybjUAAAABAAAAAmtrAAAAAAACAAAAAQAAAABMLHLkd+XPHiGJql99ZR03KPZc4DkCSa3MkpoyR2OeFgAAAAEAAAAAhXDgzCDFbZzS5EY+603+/WafaCiCd+n0OVyuZxbaQXgAAAABVEZUQQAAAAB70HIx4bTEOimcAcX4pG5p9XLfBM2PYdPQrc+zss4NhQBCrhjMuJQAAAAAAQAAAABMLHLkd+XPHiGJql99ZR03KPZc4DkCSa3MkpoyR2OeFgAAAAEAAAAAFOaJWE/fGKg5larzbZSNG34fnAB2KmsGqouij+q6Qh0AAAABVEZUQQAAAAB70HIx4bTEOimcAcX4pG5p9XLfBM2PYdPQrc+zss4NhQAAAAAAD0JAAAAAAAAAAAGn2FUyAAAAQIqcbD4lvSSQmfXVT1FuelbIexw1zY44nGvyIMJ5NVSkbmUBdhls4pRuqWP2cJFXRtCmgI/XColcvAx2gXhZxgA="

**Comment by robvanmieghem** [comment]
now this is very weird, the payment operation itself is not touched in the service, I added some padding to it ( since the python base64 decoder is a bit more strict) and tried on testnet:
```
curl -H "Content-Type: application/json" -d '{ "args": { "transaction": "AAAAAEwscuR35c8eIYmqX31lHTco9lzgOQJJrcySmjJHY54WAAAAAAAADPkAAAACAAAAAQAAAAAAAAAAAAAAAF6xghsAAAABAAAAAAAAAAEAAAABAAAAAEwscuR35c8eIYmqX31lHTco9lzgOQJJrcySmjJHY54WAAAAAQAAAACFcODMIMVtnNLkRj7rTf79Zp9oKIJ36fQ5XK5nFtpBeAAAAAFURlRBAAAAAHvQcjHhtMQ6KZwBxfikbmn1ct8EzY9h09Ctz7Oyzg2FAEKuGII3F4AAAAAAAAAAAA===" }}' "https://testnet.threefold.io/threefoldfoundation/transactionfunding_service/fund_transaction" 
{"transaction_xdr": "AAAAAKJqHzkJ4L8ismnvD+GMJGeewuGFsrAEw4l0pWcGbIVsAAAAyAAACzQAAAAWAAAAAQAAAAAAAAAAAAAAAF6xghsAAAABAAAAAAAAAAIAAAABAAAAAEwscuR35c8eIYmqX31lHTco9lzgOQJJrcySmjJHY54WAAAAAQAAAACFcODMIMVtnNLkRj7rTf79Zp9oKIJ36fQ5XK5nFtpBeAAAAAFURlRBAAAAAHvQcjHhtMQ6KZwBxfikbmn1ct8EzY9h09Ctz7Oyzg2FAEKuGII3F4AAAAABAAAAAEwscuR35c8eIYmqX31lHTco9lzgOQJJrcySmjJHY54WAAAAAQAAAAAU5olYT98YqDmVqvNtlI0bfh+cAHYqawaqi6KP6rpCHQAAAAFURlRBAAAAAHvQcjHhtMQ6KZwBxfikbmn1ct8EzY9h09Ctz7Oyzg2FAAAAAAAPQkAAAAAAAAAAAQZshWwAAABAYbCQDN/TDRkuGB/kzyXhup9E4X8/UXRZxuKXQDZ82WPud9kFH5zofxA4MbkIWhpe//WjC0QwwwyqGpmKy6QyDQ=="}
```
which is correct

**Comment by tobiaschielens** [comment]
Yes seems to be fixed

**Comment by robvanmieghem** [comment]
issue is found, also the reason why it worked sometimes and sometimes not.

**Comment by robvanmieghem** [comment]
deployed to testnet
