### ISSUE TITLE
i did not receive any freeftf on mainnet

### ISSUE THREAD

**Issue by grimpy** [threefoldfoundation/tft-stellar#126]
I went to https://www.getfreetft.threefold.io/
filled in the for passed my wallet address: GDMJ66IN7N62TBXFKYGJOH7BD7VRUSJLIY5DMGNMWBCCSG2GLGHSCTHU

didnt receive any freetft after couple of days

**Comment by gmachtel** [comment]
Apparently there is an issue with the application form, the e-mails don’t arrive.

**Comment by zaibon** [comment]
What has been done for this issue to be fixed ? @VonSub ?

**Comment by VonSub** [comment]
@zaibon the form is back to normal (testing now daily). and all tokens requested are sent out.
