### ISSUE TITLE
transaction funding service rounds amounts on testnet

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tft-stellar#127]
I installed the transactionfunding service locally on commit: e715f119713abd31e6bfa42a84749f806dd91c33
I am working on the Jumpscale Libs on commit: https://github.com/threefoldtech/jumpscaleX_libs/commit/825e99f7601cc3bfef2738be080f32834859d26a
Stellar sdk version: `stellar-sdk (2.2.3)`

Connected to my local transaction funding service I cannot reproduce the rounding of amounts when the transaction as xdr comes back from the service.

Things go wrong connected to the testnet service and passing the transaction

1. outgoing tx to the service
```
AAAAALX7uq+eXcgHVVKPAjAjscsoT2lnDH4ucBIuB6toxeoiAAAAZAAAC60AAAE9AAAAAQAAAAAAAAAAAAAAAF6yrQ4AAAABAAAAAjspAAAAAAABAAAAAQAAAAC1+7qvnl3IB1VSjwIwI7HLKE9pZwx+LnASLgeraMXqIgAAAAEAAAAAW5hxFJxBvsOK/sZDAOTRJpdvFGScYnInwuPJ2vYXCtsAAAABVEZUAAAAAAA5/GQbeotMseuGw9LomxJQHv5mNT8nihPVgEwpv/efZAAAAAA+n+iYAAAAAAAAAAA=
```

2. when it comes back from the service
```
AAAAAGOSa7nPIbsXi4WIKNV5e8wjPSBe1A5ALdfb58NKMLEfAAAAyAAACy4AAAAVAAAAAQAAAAAAAAAAAAAAAF6yrQ4AAAABAAAAAjspAAAAAAACAAAAAQAAAAC1+7qvnl3IB1VSjwIwI7HLKE9pZwx+LnASLgeraMXqIgAAAAEAAAAAW5hxFJxBvsOK/sZDAOTRJpdvFGScYnInwuPJ2vYXCtsAAAABVEZUAAAAAAA5/GQbeotMseuGw9LomxJQHv5mNT8nihPVgEwpv/efZAAAAAA+n+f4AAAAAQAAAAC1+7qvnl3IB1VSjwIwI7HLKE9pZwx+LnASLgeraMXqIgAAAAEAAAAAFOaJWE/fGKg5larzbZSNG34fnAB2KmsGqouij+q6Qh0AAAABVEZUAAAAAAA5/GQbeotMseuGw9LomxJQHv5mNT8nihPVgEwpv/efZAAAAAAAD0JAAAAAAAAAAAFKMLEfAAAAQNTnDmTSOYRNEWwHHt6/voZRq7iISjVMAN3t8pgLA8ELIsXCWJQ5fNbsjMNZ+b55EMHOtqH5AHeFWWLdU0tY+Qw=
```

you can see inside the xdr that the amount has changed from `105.066716` to `105.0667`

**Comment by robvanmieghem** [comment]
deployed on testnet
reopened for verification
