### ISSUE TITLE
Conversion goes wrong on locked tokens

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/tft-stellar#130]
**Repro steps**
1) Have a wallet on revine with locked TFT and non locked TFT
2) Convert to stellar

**Expected Result**
- non locked TFT becomes TFTA
- Locked TFT before 1 jan 2021 becomes locked TFTA
- Locked TFT after 31 december 2020 becomes locked TFT

**Actual Result**
only the non locked TFT is converted, locked is gone
400 error on the migrate tokens call 
![image](https://user-images.githubusercontent.com/59569757/81211642-f3d64a00-8fd3-11ea-907a-5040895915e8.png)

{"error": "unsupported format string passed to Currency.__format__"}

On retry =>
![image](https://user-images.githubusercontent.com/59569757/81211742-19fbea00-8fd4-11ea-9af0-a9e77ce971b4.png)

**System Info**

**Comment by DylanVerstraete** [comment]
can you give me the rivine unlockhash?

**Comment by ken-de-moor** [comment]
@DylanVerstraete 

https://explorer.testnet.threefoldtoken.com/hash.html?hash=01326d34d3cdd8e8de69b80c4ebd91959609198a30696d90863d15be10497c61fb9c09301ebee4

**Comment by DylanVerstraete** [comment]
Thanks, should be fixed soon

**Comment by robvanmieghem** [comment]
reopened for validation
