### ISSUE TITLE
Liquid exchange question: how to deposit TFT to exchange

### ISSUE THREAD

**Issue by gmachtel** [threefoldfoundation/tft-stellar#133]
We had a question from Liquid about depositing TFTs on their exchange: 

> "Threefold Network is using UTXO model. And also support message in tx. 
> To deposit TFT to exchange, we should either let users use
> - same address and different messages
> - different addresses
> **Which is the one suitable for ThreeFold?**
> 
> We implement cold wallet for any listing currency here, so the server couldn’t access any private key.
> Some guidelines for decision: 
> - Multiple addresses, is suitable for networks that let the server generating address from a master public key using HD Wallet. 
> - Single address, but multiple messages, is suitable for the networks that support memo in transaction. 
> 
> We found that, we might meet some difficulties for both cases:
> - If we use different addresses, we need to generate them offline because the server could not access the seed
> - If we use memo in transaction, we could only support one withdrawal at a time (ThreeFold uses UTXO, so the first one spent, then use it for the second one)
> (TFT use Ed25519, so we could not use master public key for the first one)."

**Comment by robvanmieghem** [comment]
I don't get it, they are referring to the rivine implementation instead of custom assets on Stellar
