### ISSUE TITLE
Tokens are duplicated on conversion

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldfoundation/tft-stellar#135]
We were able to convert the same account twice leading to a duplication of the amount of tokens:
![image](https://user-images.githubusercontent.com/17977313/81301699-add3c180-9079-11ea-9fec-44493cb46c7f.png)

**Comment by robvanmieghem** [comment]
should be fixed in 58041c28a08df0e18e787757f56b3baf415cf6f3 but blocked by https://github.com/threefoldtech/jumpscaleX_core/issues/813

**Comment by robvanmieghem** [comment]
boundary issue in the jsx console, not showing more than 50 wallets in the completion

**Comment by robvanmieghem** [comment]
deployed to testnet

**Comment by robvanmieghem** [comment]
seems fixed
