### ISSUE TITLE
document zdb slave setup for the unlock service

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#136]

**Comment by DylanVerstraete** [comment]
Right now replication is not possible for zdb's. A workaround might be to periodically store backups. @robvanmieghem is this viable?
 
There are some open issues for it: https://github.com/threefoldtech/0-db/issues

@maxux is aware of it and is working on a fix for it asap.

**Comment by robvanmieghem** [comment]
well, if there is no other option for now, it must be done through backups.

**Comment by DylanVerstraete** [comment]
these manual backups can be done using bcdb exports.
