### ISSUE TITLE
Document how to start actors individually 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#15]
Currently the readme states `p.threefoldfoundation.tft_stellar.start()` which starts all actors
It would be better if to document how to start the actors individually since not all of them should be enabled by default on a specific service

**Comment by DylanVerstraete** [comment]
We now have a folder ThreeBotPackages, each sub folder can be installed as a seperate package.

https://github.com/threefoldfoundation/tft-stellar/commit/1bc096c9b5fa74882794a46bba3eb9bcb0bafd21
