### ISSUE TITLE
After conversion, locked tokens are not shown, only 12 locked transactions got converted, others are not.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/tft-stellar#153]
Rivine : https://explorer.threefoldtoken.com/hash.html?hash=01bc1cc9289e9b3ad2d506a477362dd78b48fb6089c6dec10b6a4fdb63e2c6d5c5646619653fc9

Has exactly 31 locked transactions on rivine, 104,118.222222222 * 31 = 
3,227,664.888888882 TFT

After conversion =>
![image](https://user-images.githubusercontent.com/59569757/82654274-c1a62880-9c20-11ea-8896-495c08398cc0.png)

Exactly 3 * 104,118.222222222 TFTA and 9 * 104,118.222222222 TFT

So only 12 out of the 31 got converted.

**Comment by robvanmieghem** [comment]
@ken-de-moor do you know the stellar address?

**Comment by ken-de-moor** [comment]
@robvanmieghem  GCPFF2JYUXW5WYSVSZRIOM3NGQQ7TSKHPN6K7GKGZIL5CHGPU6NTBSG5

**Comment by robvanmieghem** [comment]
@ken-de-moor I see 31 locked token conversions (24TFT  and 7 TFTA)

Deauthorization transaction: a1db55d58f876d576c63361a45112f740472bb254e007b62937681e852ed88d7
Stellar wallet address: GCPFF2JYUXW5WYSVSZRIOM3NGQQ7TSKHPN6K7GKGZIL5CHGPU6NTBSG5
Tfchain TFT: 3895634.709999982 Free: 667969.8211111 Locked: 3227664.888888882
Tokens issued: 3895634.7099993 Free: 667969.8211111 Locked: 3227664.8888882

**Comment by ken-de-moor** [comment]
User reported it is fixed
