### ISSUE TITLE
TF Account conversion fails with errorlog : 'cursor',

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/tft-stellar#154]
This keeps happening no matter how many times the user restarts their app. See logging included.

[
    0 : {
        timestamp : Fri, 22 May 2020 08:56:16 GMT,
        message : I'm a debug message!,
        ctx : [VAR: UNDEFINED],
        level : INFO,
    },
    1 : {
        timestamp : Fri, 22 May 2020 08:56:17 GMT,
        message : startedWallet,
        ctx : [VAR: UNDEFINED],
        level : INFO,
    },
    2 : {
        timestamp : Fri, 22 May 2020 08:56:17 GMT,
        message : initialize,
        ctx : [VAR: UNDEFINED],
        level : INFO,
    },
    3 : {
        timestamp : Fri, 22 May 2020 08:56:17 GMT,
        message : initializeSingleAccount,
        ctx : {
            index : 0,
            revine : 0133a9a62d1d392317b02dbb6a401f3669c8c7ee968fa52d4084989fd744638623c24e9df2faa5,
            stellar : GCE4MAASAFI3AT3U7CCDJ5OGZGWNUQ2CE2Q6V3HVNKEF2UJI3RPWPTWG,
        },
        level : INFO,
    },
    4 : {
        timestamp : Fri, 22 May 2020 08:56:17 GMT,
        message : initializeSingleAccount,
        ctx : {
            index : 1,
            revine : 015d97ea5ef9872f76e44658e831245971d9f8662d881a37a3db25b149b6c0d8ca6b6afb849683,
            stellar : GDMNEQ7SINHKUDIZOTZQWALE3SKYXCUYV727G7JLJCVMUFMJ7QGXXAQA,
        },
        level : INFO,
    },
    5 : {
        timestamp : Fri, 22 May 2020 08:56:17 GMT,
        message : initializeSingleAccount,
        ctx : {
            index : 0,
            revine : 01135e426c87b8e9cf6a21dd4b3afbb6a26003152999c4fb1382053260e550ac49237611f10f44,
            stellar : GAHJJMT3RPDUADEUF6MC2OJZQVQUGJ2V5SEKHEKZ3RC75624VMR5QZDQ,
        },
        level : INFO,
    },
    6 : {
        timestamp : Fri, 22 May 2020 08:56:18 GMT,
        message : error convertTfAccount failed,
        ctx : {
            error : Error: Request failed with status code 400,
        },
        level : ERROR,
    },
    7 : {
        timestamp : Fri, 22 May 2020 08:56:18 GMT,
        message : Conversion TF Account error ,
        ctx : {
            errorlog : 'cursor',
        },
        level : ERROR,
    },
    8 : {
        timestamp : Fri, 22 May 2020 08:56:18 GMT,
        message : error convertTfAccount failed,
        ctx : {
            error : Error: Request failed with status code 400,
        },
        level : ERROR,
    },
    9 : {
        timestamp : Fri, 22 May 2020 08:56:18 GMT,
        message : Conversion TF Account error ,
        ctx : {
            errorlog : /explorer/hashes/0133a9a62d1d392317b02dbb6a401f3669c8c7ee968fa52d4084989fd744638623c24e9df2faa5: GET: no content available (code: 204),
        },
        level : ERROR,
    },
    10 : {
        timestamp : Fri, 22 May 2020 08:56:18 GMT,
        message : error convertTfAccount failed,
        ctx : {
            error : Error: Request failed with status code 400,
        },
        level : ERROR,
    },
    11 : {
        timestamp : Fri, 22 May 2020 08:56:18 GMT,
        message : Conversion TF Account error ,
        ctx : {
            errorlog : /explorer/hashes/015d97ea5ef9872f76e44658e831245971d9f8662d881a37a3db25b149b6c0d8ca6b6afb849683: GET: no content available (code: 204),
        },
        level : ERROR,
    },
    12 : {
        timestamp : Fri, 22 May 2020 08:56:18 GMT,
        message : error Something went wrong while fetching account,
        ctx : {
            e : NotFoundError: Not Found,
        },
        level : ERROR,
    },
    13 : {
        timestamp : Fri, 22 May 2020 08:56:19 GMT,
        message : error Something went wrong while generating account,
        ctx : {
            e : Error: Request failed with status code 400,
        },
        level : ERROR,
    },
    14 : {
        timestamp : Fri, 22 May 2020 08:56:19 GMT,
        message : error initializeImportedPkidAccounts,
        ctx : {
            error : Error: Something went wrong while generating account,
        },
        level : ERROR,
    },
]

**Comment by robvanmieghem** [comment]
jumpscale libs bug: https://github.com/threefoldtech/jumpscaleX_libs/issues/219
