### ISSUE TITLE
Sms activation fails for newly created 3bot accounts

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/tft-stellar#155]
1) Create an entirely new 3bot connect account
2) Attempt to go to the wallet

Logging =>

[
    0 : {
        timestamp : Fri, 22 May 2020 17:13:30 GMT,
        message : I'm a debug message!,
        ctx : [VAR: UNDEFINED],
        level : INFO,
    },
    1 : {
        timestamp : Fri, 22 May 2020 17:13:30 GMT,
        message : startedWallet,
        ctx : [VAR: UNDEFINED],
        level : INFO,
    },
    2 : {
        timestamp : Fri, 22 May 2020 17:13:30 GMT,
        message : initialize,
        ctx : [VAR: UNDEFINED],
        level : INFO,
    },
    3 : {
        timestamp : Fri, 22 May 2020 17:13:36 GMT,
        message : initializeSingleAccount,
        ctx : {
            index : 0,
            revine : 01660ba72e55e2abd2f33d6091e174c7bef3c21be604872a4bfca3219eef4d2cc22faa24173bab,
            stellar : GAA7FTTVBBQTXL46JQDQSVK3SBESFIGVQQO6G3QEZODX7WW7YO3YPM6C,
        },
        level : INFO,
    },
    4 : {
        timestamp : Fri, 22 May 2020 17:13:36 GMT,
        message : error convertTfAccount failed,
        ctx : {
            error : Error: Request failed with status code 400,
        },
        level : ERROR,
    },
    5 : {
        timestamp : Fri, 22 May 2020 17:13:36 GMT,
        message : Conversion TF Account error ,
        ctx : {
            errorlog : /explorer/hashes/01660ba72e55e2abd2f33d6091e174c7bef3c21be604872a4bfca3219eef4d2cc22faa24173bab: GET: no content available (code: 204),
        },
        level : ERROR,
    },
    6 : {
        timestamp : Fri, 22 May 2020 17:13:36 GMT,
        message : start Sms Flow,
        ctx : [VAR: UNDEFINED],
        level : INFO,
    },
    7 : {
        timestamp : Fri, 22 May 2020 17:13:37 GMT,
        message : error generateActivationCode failed,
        ctx : {
            e : Error: Request failed with status code 400,
        },
        level : ERROR,
    },
    8 : {
        timestamp : Fri, 22 May 2020 17:13:37 GMT,
        message : init error,
        ctx : {
            error : Error: Request failed with status code 400,
        },
        level : ERROR,
    },
]

**Comment by robvanmieghem** [comment]
@ken-de-moor can you try this on testnet?

**Comment by ken-de-moor** [comment]
Issue is resolved by now
