### ISSUE TITLE
User is missing 100.000 TFTA after conversion

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/tft-stellar#166]
https://explorer.threefoldtoken.com/hash.html?hash=01c5cbc94ec12501b4000bac40e8e84d6c5526fd68805e588a7099e099e26dbf97b6d4edb56ddf

https://stellar.expert/explorer/public/account/GAY3QF532Z3N7HN7DYXAKLLZMLS4NRJMZZHPIHGIR2SXT4IMTYNUAG3J

We have confirmed this is the correct wallet fetched in the app, but for some reason it does not have the 100.000 TFTA it is supposed to have while it had 100.000 TFT on rivine.

        timestamp : Mon, 08 Jun 2020 11:49:47 GMT,
        message : initializeSingleAccount,
        ctx : {
            index : 1,
            revine : 01c5cbc94ec12501b4000bac40e8e84d6c5526fd68805e588a7099e099e26dbf97b6d4edb56ddf,
            stellar : GAY3QF532Z3N7HN7DYXAKLLZMLS4NRJMZZHPIHGIR2SXT4IMTYNUAG3J,
        },
        level : INFO,

**Comment by robvanmieghem** [comment]
The address  was stored in the local db for duplicate conversion protection but was not converted yet. Removed the address from the local db and executed the conversion call through curl, the user has his tfta now. Probably happened when I upgraded production.
