### ISSUE TITLE
Imported account is missing TFT, but is successfully migrated

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/tft-stellar#169]
018eea3bcb72ef093982ca75de5987982f5ff2081ba14ed612e279b5ec7a41353feae0be2c9fb5
GDR5QRMQI7FZCHXLPO43CDZN26U7Q5BNGZIQNUXYVRKGP27IFRIWXWZY

https://explorer.threefoldtoken.com/hash.html?hash=018eea3bcb72ef093982ca75de5987982f5ff2081ba14ed612e279b5ec7a41353feae0be2c9fb5

https://stellar.expert/explorer/public/account/GDR5QRMQI7FZCHXLPO43CDZN26U7Q5BNGZIQNUXYVRKGP27IFRIWXWZY

 timestamp : Fri, 19 Jun 2020 18:57:02 GMT,
        message : initializeSingleAccount,
        ctx : {
            index : 0,
            revine : 018eea3bcb72ef093982ca75de5987982f5ff2081ba14ed612e279b5ec7a41353feae0be2c9fb5,
            stellar : GDR5QRMQI7FZCHXLPO43CDZN26U7Q5BNGZIQNUXYVRKGP27IFRIWXWZY,
        }

**Comment by robvanmieghem** [comment]
removed the  from the  concurrency lock db and executed again
