### ISSUE TITLE
Imported account is missing TFT

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/tft-stellar#180]
stellar ; GB2I6PJZ5RHMNW4Z7LEMD7KYADKKFOHT7F72J4S6ATW7AW4QZ5TBRGIF
rivine ; 010226791dc5f8037c621b0cdda1df70055b9750d74bb4657c2164d8588276beee923f2daaf6e9

Seems to be migrated but no tokens got deposited. concurrency lock db issue maybe?

**Comment by robvanmieghem** [comment]
it was indeed a concurrency lock db issue, is fixed and the tokens have been transferred
