### ISSUE TITLE
rest service to get tft/tfta insight and stats 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#182]
using js-sdk

Gets updated every 10 minutes with the data from https://github.com/threefoldfoundation/tft-stellar/issues/179

example response:
```json
[{ "asset":"TFT",  "issuer": "GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47", "total": 456315846.6386806, "num_accounts": 2494, "locked":[{"until":2021-04-21T18:25:43-05:00, "amount":5000},{"until":2022-04-21T18:25:43-05:00, "amount":10000}]},
{"asset":"TFTA",...

]
```
Please deploy on statsdata.threefoldtoken.com and if possible set the CORS header

**Comment by waleedhammam** [comment]
readme: https://github.com/threefoldtech/js-sdk/blob/42797e26dbb24800d797576010caa432e1da12a5/jumpscale/packages/stellar_stats/README.md#L1

![Screenshot from 2020-07-26 11-59-25](https://user-images.githubusercontent.com/10658229/88476490-217ac180-cf39-11ea-807f-5bd1e0229fc2.png)
![Screenshot from 2020-07-26 11-45-49](https://user-images.githubusercontent.com/10658229/88476493-22abee80-cf39-11ea-94b2-4d33f980cdb5.png)

**Comment by waleedhammam** [comment]
deployed on https://statsdata.threefoldtoken.com/
examples:

https://statsdata.threefoldtoken.com/stellar_stats/api/stats
https://statsdata.threefoldtoken.com/stellar_stats/api/stats?network=public

**Comment by robvanmieghem** [comment]
thanks @waleedhammam
