### ISSUE TITLE
Multisig for the July minting 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#194]
- the minting is done by the core minting code
- all minting proofs are as always attached to the minting transactions (proof capacity is there)
- the multi sig parties run the verification scripts
- 5 out of 7 need to agree (new) on validation action
- they all need to forward their check to the next person only if 5 agreed and found concensus the minting can be accepted
- the multisignature is on stellar blockchain

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/5029236/payouts_signed_by_ahmed.txt)


please next execute 
python3 sign.py payouts_signed_by_ahmed.txt payouts_signed_by_wenand.txt

**Comment by weynandkuijpers** [comment]
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/5029317/payouts_signed_by_weynand.txt)

Please next signer execute this file.

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/5029565/payouts_signed_by_nickolay.txt)
 Please next one :)

**Comment by AdnanFatayerji** [comment]
[payouts_signed_by_adnan.txt](https://github.com/threefoldfoundation/tft-stellar/files/5029751/payouts_signed_by_adnan.txt)
Thanks Reem & Thabet! On to the next one :)

**Comment by Nayer-Sobhy** [comment]
signed and submitted
Thanks Rob, Reem and Thabet
