### ISSUE TITLE
 FreeTFT  stats on https://statsdata.threefoldtoken.com/ do not work

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#196]
https://statsdata.threefoldtoken.com/stellar_stats/api/stats?network=public&tokencode=FreeTFT&detailed=true
![Screenshot 2020-08-07 at 08 13 32](https://user-images.githubusercontent.com/3511318/89615012-eb690600-d885-11ea-8469-d37373fa05a5.png)

**Comment by waleedhammam** [comment]
works now: https://statsdata.threefoldtoken.com/stellar_stats/api/stats?network=public&tokencode=FreeTFT&detailed=true
