### ISSUE TITLE
https://statsdata.threefoldtoken.com/ is slow

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#197]
Reusing the statistics collector would prevent fetching the  unlocktransactions every time.
It does not prefetch the data every 10 minutes like mentioned in the spec

**Comment by waleedhammam** [comment]
added caching every 10 mins: https://github.com/threefoldtech/js-sdk/commit/be7bba028a9775f716f85a7e8a06125a24794c06

**Comment by robvanmieghem** [comment]
I don't see a reason why it should be stored in Redis, collecting the stats would also be greatly sped up if the statistics collector instance is reused

**Comment by robvanmieghem** [comment]
do this one first: Move the stellar stats service from js-sdk to this repo #204
