### ISSUE TITLE
Location of the stellar stats service

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#198]
why is it located in at https://github.com/threefoldtech/js-sdk/tree/development/jumpscale/packages/stellar_stats and not in this repo?

**Comment by waleedhammam** [comment]
It's because all the packages in this repo is jsx based, Maybe create a new dir and copy the package into it would be okay ?

**Comment by robvanmieghem** [comment]
The jsx packages in this repo actually need to be converted to js-ng packages

**Comment by robvanmieghem** [comment]
I created an issue for the move : https://github.com/threefoldfoundation/tft-stellar/issues/204 and other issues to convert the services to js-ng
