### ISSUE TITLE
Convert the conversion service to js-ng

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#200]
and while at it, rename it to tfchainmigration service

**Comment by robvanmieghem** [comment]
blocked on https://github.com/threefoldtech/js-sdk/issues/1120

**Comment by robvanmieghem** [comment]
not blocked, even though it would make life simpler

**Comment by ranatrk** [comment]
WIP https://github.com/threefoldfoundation/tft-stellar/tree/development_tfchainmigration_jsng
converted the package structure to fit jsng, but still working on usage of  tfchain(from `lib/stats/` in current repo)  in the package as imports outside the package isn't straightforward

**Comment by ranatrk** [comment]
progress:
- fixed imports to import tfchain types and client functions from `scripts/conversion/` 
- fixed code tht wasnt changed during the package conversion from jsx to js-ng package
- package now is added successfully with no errors

TODO: `authcoin` used with tfchain old client not found in `scripts/conversion/` client code in current repo, will look into importing it or changing it

**Comment by ranatrk** [comment]
PR includes:
- convert package to jsng
- add backward compatibility in actor request bodies to be in the form `{args:{......}`
- import some functions from tfchain client to the package
