### ISSUE TITLE
Convert the transaction funding service to js-ng

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#201]

**Comment by robvanmieghem** [comment]
blocked on https://github.com/threefoldtech/js-sdk/issues/1120

**Comment by robvanmieghem** [comment]
not blocked even though it would make life simpler

**Comment by ranatrk** [comment]
WIP: https://github.com/threefoldfoundation/tft-stellar/commit/ee488df422363e17aeb76840496c7a6aa2cd1c57
converted package to be jsng package, still needs to be well tested
