### ISSUE TITLE
convert the unlock service to js-ng

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#202]
We also need a migration strategy for the current data

**Comment by robvanmieghem** [comment]
blocked on https://github.com/threefoldtech/js-sdk/issues/1120

**Comment by robvanmieghem** [comment]
not blocked but would make it easier

**Comment by ranatrk** [comment]
scripts to export and import the current data: https://github.com/threefoldfoundation/tft-stellar/pull/230/commits/bc4dafd0a79b50c0cd30640934fb057d21874606
The export exports the data from bcdb as a list of json objects into the specified destination file, while the import imports tht data and saves it using the model in jsng
The export needs to be done from the shell itself, while the import is done with click and the file can simply be run providing the destination the export was done in
