### ISSUE TITLE
TFT Stats REST API for Coingecko

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/tft-stellar#206]
In our TFT Stats REST API (https://statsdata.threefoldtoken.com/stellar_stats/api/stats?network=public&tokencode=TFT&detailed=true) we need two additional links (API endpoints) that will return only one number each:
1. Total number of TFT
2. Number of Unlocked TFT

Example: http://horizon.tfgw-prod-05.gateway.tf/tft_supply

This data is required by third-party websites like https://www.coingecko.com/en/coins/threefold-token and https://coinmarketcap.com/ to show our circulating supply

Related Promo Circle story: https://circles.threefold.me/project/despiegk-tf_team_grid/us/1183

**Comment by robvanmieghem** [comment]
@nbabenko  how do we handle the TFTA/TFT distinction? not?

**Comment by nbabenko** [comment]
I propose to let TFTA outside of equation for now. 
1. TFTA are not tradable on other exchanges except stellar dex 
2. TFTA trades and volumes will not be counted on tokens stats by explorers, because its technically another token. 
3. We could add apis for TFTA specific numbers later if needed.

**Comment by robvanmieghem** [comment]
@waleedhammam Can we add this as extra endpoints to the existing stastistics service?

**Comment by nbabenko** [comment]
@waleedhammam any updates on this? We need this for coinmarketcap too.

**Comment by xmonader** [comment]
@robvanmieghem @nbabenko are their specific endpoints for the endpoints e.g total_tft, num_unlocked_tokens? expected responses

**Comment by nbabenko** [comment]
yes, we need separate endpoints for both of this numbers separately. API response should be ONLY single number (without brackets, any other symbols, etc). 
Comment with example from coinmarketcap:

"API endpoint that displays ONLY 'Total Supply' as a numerical value (e.g. http://chainz.cryptoid.info/grs/api.dws?q=totalcoins)
Total Supply = # of coins in existence right now (minus any coins that have been verifiably burned)."

**Comment by xmonader** [comment]
https://statsdata.threefoldtoken.com/stellar_stats/api/total_unlocked_tft
https://statsdata.threefoldtoken.com/stellar_stats/api/total_tft

**Comment by xmonader** [comment]
@nbabenko once verified please close the issue

**Comment by nbabenko** [comment]
nice, thank you! Looks correct!
