### ISSUE TITLE
Foundation Wallets addresses for Coingecko disclosure

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/tft-stellar#207]
Hi, 

For the Coingecko ranking we have to provide a spreadsheet list of the Token Distribution details | For top 20 wallets AND team/development/foundation wallets, airdrop/distribution holdings, marketing funds, vesting funds or any locked up supply.

Example: https://docs.google.com/spreadsheets/d/1a79iZ4eLSUFEPaqHShdnyWjlzefcXA7jcKYwX8xPxZw/edit#gid=0

**Comment by robvanmieghem** [comment]
@nbabenko is this still relevant?

**Comment by robvanmieghem** [comment]
@nbabenko The foundation walletsare available in the wiki through the statistics service

**Comment by nbabenko** [comment]
I believe we already have everything in the detailed API and in the wiki. Submitted update to the coinmarketcap, waiting for their feedback. Thank you!

**Comment by nbabenko** [comment]
not actual anymore
