### ISSUE TITLE
prevent activation account draining phase1

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#209]
Besides costing us XLM, when drained, no more normal account activations can happen ( both for the 3bot connect app wallet as the inialization of the 3bots)

Critical:
- [x] Use sponsored reserves in the activation service #256

**Comment by MathiasDeWeerdt** [comment]
Identified an IP that had created over 250+ accounts in past 14 days and was still producing more. 
We clear malintent and fake account names / emails.

Blocked this ip from creating anymore accounts and we'll be monitoring closely.

**Comment by robvanmieghem** [comment]
Thanks @MathiasDeWeerdt but It is still being drained

**Comment by robvanmieghem** [comment]
Instead of making changs to the js-sdk version, first convert the activation service to js-ng: #199

**Comment by robvanmieghem** [comment]
https://developers.stellar.org/docs/glossary/sponsored-reserves/ seems like a clean solution.

**Comment by robvanmieghem** [comment]
One of the problems isalso: [A testnet 3bot creates and initialises a mainnet wallet](https://github.com/threefoldtech/js-sdk/issues/1572)
