### ISSUE TITLE
Multisig for the August minting

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#210]

**Comment by xmonader** [comment]
my signed payouts 
[payouts_signed_by_Ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/5166874/payouts_signed_by_Ahmed.txt)

for the next signer please do

./sign.py payouts_signed_by_Ahmed.txt payouts_signed_by_YOUR_NAME.txt

**Comment by nbabenko** [comment]
my signatures
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/5169096/payouts_signed_by_nickolay.txt)

**Comment by Nayer-Sobhy** [comment]
my signed payouts 
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/5170167/payouts_signed_by_nayer.txt)

**Comment by weynandkuijpers** [comment]
Payouts signed be me:
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/5170988/payouts_signed_by_weynand.txt)

**Comment by BenjellounO** [comment]
Payouts signed by me: 

[payouts_signed_by_oussama.txt](https://github.com/threefoldfoundation/tft-stellar/files/5172073/payouts_signed_by_oussama.txt)

**Comment by robvanmieghem** [comment]
weyands's signatures are invalid

**Comment by BenjellounO** [comment]
Payouts signed by me - based on Nayer's sigantures
[payouts_signed_by_oussama.txt](https://github.com/threefoldfoundation/tft-stellar/files/5174302/payouts_signed_by_oussama.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_Ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/5176464/payouts_signed_by_Ahmed.txt)
my remaining payouts

**Comment by Nayer-Sobhy** [comment]
remaining payouts

[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/5176803/payouts_signed_by_nayer.txt)

**Comment by BenjellounO** [comment]
Remaining payouts 

[payouts_signed_by_oussama.txt](https://github.com/threefoldfoundation/tft-stellar/files/5177999/payouts_signed_by_oussama.txt)

**Comment by weynandkuijpers** [comment]
Remaining payouts

[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/5178098/payouts_signed_by_weynand.txt)
