### ISSUE TITLE
testnet TFT faucet

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#212]
a simple js-ng rest service that take a Stellar address as input and transfers 10000 testnet TFT's to it from a prefunded wallet that is an install arguments of the package

**Comment by ranatrk** [comment]
WIP : https://github.com/threefoldfoundation/tft_faucet/commit/75a04535a7efb05e061970805f32d8209742923c

**Comment by robvanmieghem** [comment]
@ranatrk  can't we put it in this repo instead of creating a new one?

**Comment by ranatrk** [comment]
> @ranatrk can't we put it in this repo instead of creating a new one?
It can be added, but the components of the package will need to be in the base of the repo to be able to import it in js-ng. That is why we created a new repo to include it there.

> There is no need to keep the old FreeTFT faucet and no need for 3bot connect authentication in the UI
> The UI can also be put in a later FR, it is not that urgent
okay, will just finalise what we have so far now then

**Comment by ranatrk** [comment]
Machine deployed with package added :
- IP: 164.90.179.56
- Domain: https://gettft.testnet.grid.tf

**Comment by robvanmieghem** [comment]
thanks @ranatrk . Looking at the code of the packagemanager ( https://github.com/threefoldtech/js-sdk/blob/7a11f1b51d7b3346fe147a8908fdba1d4c8e0cd2/jumpscale/servers/threebot/threebot.py#L367), it looks like it should be possible to add a package that does not reside in the root of a repo
