### ISSUE TITLE
remove the 1 time  per wallet restriction from the testnet tft faucet

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#223]

**Comment by ranatrk** [comment]
Once the PR can be merged, the machine with the faucet will be updated as well

**Comment by robvanmieghem** [comment]
Thanks @ranatrk

**Comment by ranatrk** [comment]
@robvanmieghem no problem 
https://gettft.testnet.grid.tf is now updated to use package from tft-stellar repo by manually cloning and adding the package with the updated code of removing the restriction
