### ISSUE TITLE
september minting

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#225]

**Comment by Nayer-Sobhy** [comment]
my signings
[payouts_to_sign_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/5317432/payouts_to_sign_by_nayer.txt)

**Comment by BenjellounO** [comment]
[payouts_to_sign_by_oussama.txt](https://github.com/threefoldfoundation/tft-stellar/files/5318338/payouts_to_sign_by_oussama.txt)
September's payouts Signed

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/5322867/payouts_signed_by_ahmed.txt)

**Comment by maximilianrang** [comment]
[Uploading payouts_signed_by_maximilian.txt…]()
