### ISSUE TITLE
testnet services are not functioning properly 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#226]

**Comment by zaibon** [comment]
https://www.stellar.org/developers-blog/guide-to-protocol-14-prep
Did you do all the preparation for the next upgrade ?

**Comment by robvanmieghem** [comment]
thanks for the heads up but it's due to a power outage

**Comment by robvanmieghem** [comment]
my bad, I checked using a request body that is only valid for the js-ng implementation, not the jsX
