### ISSUE TITLE
Keep threebot server running

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#23]
when a kosmos session is exited, the threebot server exits as well, can I keep it running?

**Comment by zaibon** [comment]
I'm not sure how you start your 3bot, but the Default start function `j.servers.threebot.local_start_3bot` has a `background` argument that if set to true, make the 3bot starts in tmux

**Comment by robvanmieghem** [comment]
@zaibon thanks

**Comment by robvanmieghem** [comment]
@zaibon 
How do you start the services then?
```
j.servers.threebot.local_start_3bot(background=True)
# JSXOBJ:
## jumpscale.gedis.client
ID: 102
 - name                : threebot
 - host                : 127.0.0.1
 - port                : 8901
 - package_name        : zerobot.base
 - threebot_local_profile: default
 - password_           :


JSX> gedis = j.clients.gedis.get("pm", port=8901, package_name="zerobot.packagemanager")
JSX> p.threefoldfoundation.unlock_service.start()
Tue 03 07:30:52 <stdin>              -   1 - <module>                           : EXCEPTION:
    NameError("name 'p' is not defined",)
--TRACEBACK------------------
<stdin> in <module>
    1
-----------------------------

name 'p' is not defined
```

**Comment by zaibon** [comment]
I'm not sure what I'm seeing now. Starting in with `background=True` should starts everything in tmux.
If you go into tmux in the threebot_server pane, there you will find the kosmos shell where `p` is defined.

Now you can also just use a gedis client manage the package of your 3bot.
```
JSX> gedis = j.clients.gedis.get("pm", port=8901, package_name="zerobot.packagemanager")
JSX> cl.package_manager.package_add(path=....)
JSX> cl.package_manager.package_start(...)
```

**Comment by robvanmieghem** [comment]
thanks, looks like the `p.` is not available locally when started in the background but the `package_manager.package_start` command work
