### ISSUE TITLE
Description on the faucet is wrong

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#232]
Remove "You will only be able to receive tokens once." since that is not true
![Screenshot 2020-10-26 at 10 18 18](https://user-images.githubusercontent.com/3511318/97154955-e628a280-1774-11eb-841d-95e86ec768ef.png)

**Comment by ranatrk** [comment]
- Fix: https://github.com/threefoldfoundation/tft-stellar/pull/233/commits/dbf44b34f3a7cbc20f325e36342b321873118b0b
- updated https://gettft.testnet.grid.tf/
![Screenshot from 2020-10-26 11-46-17](https://user-images.githubusercontent.com/17128393/97157601-f5155200-1780-11eb-8068-3187d99293d3.png)
