### ISSUE TITLE
October minting

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#236]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/5488989/payouts_signed_by_ahmed.txt)

**Comment by Nayer-Sobhy** [comment]
here is my file 
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/5489844/payouts_signed_by_nayer.txt)

**Comment by BenjellounO** [comment]
October Payouts [payouts_signed_by_oussama.txt](https://github.com/threefoldfoundation/tft-stellar/files/5492858/payouts_signed_by_oussama.txt)

**Comment by nbabenko** [comment]
[Uploading payouts_signed_by_nickolay.txt…]()

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/5493709/payouts_signed_by_nickolay.txt)

**Comment by weynandkuijpers** [comment]
All payouts  are signed and send
