### ISSUE TITLE
November minting

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#242]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/5621333/payouts_signed_by_ahmed.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/5622308/payouts_signed_by_nickolay.txt)

**Comment by Nayer-Sobhy** [comment]
[Uploading payouts_signed_by_nayer.txt…]()

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/5627475/payouts_signed_by_nayer.txt)

**Comment by BenjellounO** [comment]
[payouts_signed_by_oussama.txt](https://github.com/threefoldfoundation/tft-stellar/files/5627836/payouts_signed_by_oussama.txt)

**Comment by weynandkuijpers** [comment]
Payouts signed.  Minting done.

[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/5629024/payouts_signed_by_weynand.txt)

**Comment by weynandkuijpers** [comment]
Fix for failed payouts signed (1st signature)

[payouts_signed_by_weynand-2.txt](https://github.com/threefoldfoundation/tft-stellar/files/5641580/payouts_signed_by_weynand-2.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/5641727/payouts_signed_by_ahmed.txt)

**Comment by BenjellounO** [comment]
[payouts_signed_by_oussama.txt](https://github.com/threefoldfoundation/tft-stellar/files/5641816/payouts_signed_by_oussama.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/5642012/payouts_signed_by_nickolay.txt)

**Comment by Nayer-Sobhy** [comment]
remaining pay outs

[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/5645287/payouts_signed_by_nayer.txt)
