### ISSUE TITLE
Make the package domains configurable

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#26]
currently it writes  `server_name ~^(www\.)?testnet.threefoldtoken.io$;` in the nginx config
It is hardcoded in the package.py files. It should be configurable or have no server_name directive for development

**Comment by robvanmieghem** [comment]
reverted the commit since it did work on the Jumpscale version on the testnet instance

**Comment by robvanmieghem** [comment]
reopened because of https://github.com/threefoldfoundation/tft-stellar/issues/43

**Comment by DylanVerstraete** [comment]
It works on my machine with all the repos set on `unstable`
```
JSX> gedis = j.clients.gedis.get("pm", port=8901, package_name="zerobot.packagemanager")
JSX> gedis.actors.package_manager.package_add(git_url="https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/activation-service", install_kwargs={ "domain": "testnet.threefold.io
   1 " })
HUP 1194
HUP 1194
b'OK'

JSX> p.threefoldfoundation.activation_service.install_kwargs
{'domain': 'testnet.threefold.io'}
```

It works in my case if I have no `threefoldfoundation` folder in `/sandbox/code/github`

**Comment by robvanmieghem** [comment]
@DylanVerstraete I did comment the specific lines  yesterday evening and pushed it

**Comment by DylanVerstraete** [comment]
@robvanmieghem oh, didn’t see. It was to good to be true :)
