### ISSUE TITLE
december minting

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#260]

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/5769738/payouts_signed_by_nayer.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/5770015/payouts_signed_by_ahmed.txt)

**Comment by weynandkuijpers** [comment]
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/5771668/payouts_signed_by_weynand.txt)

Signed and uploaded

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/5774762/payouts_signed_by_nickolay.txt)
