### ISSUE TITLE
reduce transaction fees to 0.01 

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/tft-stellar#269]
logging the issue As per @despiegk 's request 

Right now it's 0.1 TFT and doesn't really work out with the hourly billing model in the VDC
24 * 0.1 = 2.4 TFT daily
2.4*30 =  72 TFT monthly which is ~ 7 dollars

if there're any remarks please review with kds

**Comment by robvanmieghem** [comment]
todo: check  if this requires modifications to the mobile wallet

**Comment by robvanmieghem** [comment]
This requires a modification in the mobile wallet

**Comment by xmonader** [comment]
@robvanmieghem what are we going to do here? we already did the custom prices, now the they transaction fees are 72 TFT monthly, which reduce the expiration of the pools to the same day

**Comment by robvanmieghem** [comment]
blocked on https://github.com/threefoldtech/threefold_connect/issues/207

**Comment by robvanmieghem** [comment]
Implemented and deployed on testnet

**Comment by weynandkuijpers** [comment]
Changed state to verification

**Comment by robvanmieghem** [comment]
@weynandkuijpers I didn't deploy to production yet, have to perform a rolling upgrade and production does not run on kubernetes yet

**Comment by robvanmieghem** [comment]
Instead of spending my time on testing the modified and new ( since jsx does not do url rewriting properly) caddy rules locally  and deploy it on the old environment, I'll deploy it on the the ha cluster with a fallback for the not converted services to the old environment, this is time better spent.

**Comment by robvanmieghem** [comment]
Created and deployed everything but when switching the domain name  last night, the ssl certificate turned out to be invalid. Will figure out what is wrong and switch again hopefully next night. When everything goes well there will be no downtime.

**Comment by robvanmieghem** [comment]
Fixed it, turned out 1 of the 4 Ingress definitions  for the same host was not correct  making the controller serve a fake certicate for all of them.

**Comment by robvanmieghem** [comment]
Tested with the mobile wallet
