### ISSUE TITLE
January minting

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#283]

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/5912725/payouts_signed_by_nayer.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/5914268/payouts_signed_by_ahmed.txt)

**Comment by weynandkuijpers** [comment]
Payouts signed
[payouts_signed_by_weynand-jan-2021.txt](https://github.com/threefoldfoundation/tft-stellar/files/5916085/payouts_signed_by_weynand-jan-2021.txt)

**Comment by nbabenko** [comment]
[payouts_jan_2021_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/5916977/payouts_jan_2021_signed_by_nickolay.txt)

**Comment by nbabenko** [comment]
[payouts_jan_2021_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/5920177/payouts_jan_2021_signed_by_nickolay.txt)
Resigned Ahmed's output as Weynand did wrong signature

**Comment by weynandkuijpers** [comment]
[payouts_jan_2021_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/5922985/payouts_jan_2021_signed_by_weynand.txt)
