### ISSUE TITLE
Check if there is a difference between uppercase and lowercase assets

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tft-stellar#30]

**Comment by DylanVerstraete** [comment]
They don't explicity tell that there is a difference. But by the looks of it, there is.

Documentation goes as following:

To issue a new type of asset, all you need to do is choose a code. It can be any combination of up to 12 letters or numbers, but you should use the appropriate ISO 4217 code (e.g. USD for US dollars) or ISIN for national currencies or securities.

So making an asset with lowercase and uppercase letters should not be done. It should be all uppercased.

**Comment by robvanmieghem** [comment]
@DylanVerstraete Can you test if it makes a difference?

**Comment by robvanmieghem** [comment]
@DylanVerstraete gentle reminder

**Comment by robvanmieghem** [comment]
it does make a difference, when sending tft:GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3 from the issuer account GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3 to someone with a trustline to TFT:GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3
jumpscale.clients.stellar.exceptions.NoTrustLine: Receiver has no trustline
