### ISSUE TITLE
Vesting Dashboard

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#300]
see  https://github.com/threefoldfoundation/tft-stellar/blob/master/specs/vesting/vesting_dashboard.md

UI to-do details on user story here https://github.com/threefoldfoundation/tft-stellar/blob/master/specs/vesting/vesting_dashboard_userstories.md

**Comment by sasha-astiadi** [comment]
duplicate, issue: https://github.com/threefoldfoundation/tft-stellar/issues/301
