### ISSUE TITLE
Vesting Dashboard/Package

### ISSUE THREAD

**Issue by ranatrk** [threefoldfoundation/tft-stellar#301]
Specs: https://github.com/threefoldfoundation/tft-stellar/blob/master/specs/vesting/vesting_dashboard.md
Service: https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/vesting_service

- 3bot package with threefold connect login enabled
- Actor methods : recieve calls from frontend and accordingly forward them to the service 
  - [x] Create escrow account (call service), and save both addresses
  - [x] List all saved vesting accounts
- Frontend:
  - [x] Create escrow account by passing wallet address -> send request to the actor--> forward to the service
  - [x] View/List created vesting accounts
  
  
  user stories for front-end @ranatrk :
  https://github.com/threefoldfoundation/tft-stellar/blob/master/specs/vesting/vesting_dashboard_userstories.md

**Comment by sasha-astiadi** [comment]
updated the document https://github.com/threefoldfoundation/tft-stellar/blob/master/specs/vesting/vesting_dashboard_userstories.md @ranatrk

**Comment by ranatrk** [comment]
- Install package with parameters : `wallet_network` : `TEST` , and click the + button before adding package. If the network will be changed to mainnet then the wallet_network passed should be `STD`

After package is installed on threebot server, the package front end is available through `<IP>/vesting_dashboard/`

- To build frontend in frontend dir:  `npm build install`


- To create a test wallet (owner) from jsng shell:
```
wallet = j.clients.stellar.get("test_vesting",network="TEST")                                     
wallet.activate_through_friendbot()                                                                 
wallet.add_known_trustline("TFT")                                                                   
wallet.save() 
```

Things left TODO:
- Apply functionality to the transactions info button to view the transaction details in a dialog
- automatically Reload page after create vesting account is successful
- update the domain in package.toml of the package to reflect the domain to be used

**Comment by DylanVerstraete** [comment]
@ranatrk Well done on the work so far.

All that is left to do now is:

- test with tft
- deploy testnet env
- show unlockable balance

**Comment by ranatrk** [comment]
- Added viewing both Vesting and Owner balances
- Added owner accounts locked balances view
- Updated transactions view

![Screenshot from 2021-03-21 15-23-55](https://user-images.githubusercontent.com/17128393/111906512-81d6ea00-8a59-11eb-9123-961abc3892b6.png)

![Screenshot from 2021-03-21 15-21-46](https://user-images.githubusercontent.com/17128393/111906510-813e5380-8a59-11eb-9fea-f4ce13e42e3d.png)

![Screenshot from 2021-03-21 15-21-38](https://user-images.githubusercontent.com/17128393/111906505-7d123600-8a59-11eb-97c1-a73ecce23c9c.png)

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/tft-stellar/issues/310 please change the logo from 3bot into new one on this feature req
