### ISSUE TITLE
stellar metadata of tft and tfta is no longer published on threefold.io

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#306]

**Comment by robvanmieghem** [comment]
created an issue with details on what needs to be done in the website repo: https://github.com/threefoldfoundation/www_threefold_io/issues/63

**Comment by sabrinasadik** [comment]
<img width="1056" alt="Screenshot 2021-04-07 at 16 30 01" src="https://user-images.githubusercontent.com/31733464/113883586-938cf100-97be-11eb-9c8b-6922ce35a239.png">
