### ISSUE TITLE
the vesting dashboard does not redirect to the login page

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#309]
network:
![Screenshot 2021-03-22 at 13 36 46](https://user-images.githubusercontent.com/3511318/111990770-e22a6200-8b13-11eb-905b-c1f2d450958e.png)

login response:
![Screenshot 2021-03-22 at 14 10 51](https://user-images.githubusercontent.com/3511318/111994792-7696c380-8b18-11eb-9c76-4af114afe4a0.png)

![Screenshot 2021-03-22 at 13 39 19](https://user-images.githubusercontent.com/3511318/111990994-19990e80-8b14-11eb-9c4e-bbb360d53640.png)

webpage shown:
![Screenshot 2021-03-22 at 13 40 30](https://user-images.githubusercontent.com/3511318/111991091-33d2ec80-8b14-11eb-9145-6d8874491615.png)

I seems like the login response page is not rendered over the original webpage

**Comment by DylanVerstraete** [comment]
Maybe you were logged in already? Can you try again in incognito page?

**Comment by robvanmieghem** [comment]
already did and also tried chrome

**Comment by robvanmieghem** [comment]
Seems like the js-sdk environment needs a default identity for this to work
```
identity = j.core.identity.new(name="INSTANCE_NAME",tname="NAME.3bot", email="", words="",explorer_url="https://explorer.testnet.grid.tf/api/v1") 
identity.register()
identity.save()
j.core.identity.set_default(INSTANCE_NAME)
```
