### ISSUE TITLE
Migrate tokens can be used multiple times

### ISSUE THREAD

**Issue by JonasWijne** [threefoldfoundation/tft-stellar#31]
see https://testnet.steexp.com/account/GBBJPBAQ4LTFEQZJFLUER6EFLF2IN4G7OAAEHRRTTVEOMI4S2GKF4FXC 
tis adress should only have 100 TFT but has more becuase the request 
`curl -H "Content-Type: application/json" -d '{ "args": { "tfchain_address": "01548657216b984f16034c91ba3625a531e560b2aaafca467e83ab8332c0efc3158d4933f55ab5", "stellar_address": "GBBJPBAQ4LTFEQZJFLUER6EFLF2IN4G7OAAEHRRTTVEOMI4S2GKF4FXC" }}' -XPOST ` was run multiple times

**Comment by robvanmieghem** [comment]
My suggestion is to 
- [ ] check if the tfchain address is locked
- [ ] add the transaction hash of the lock transaction to the stellar payment
- [ ] check if payments to this stellar address have a transaction with this hash as memofield and from the comversion wallet
