### ISSUE TITLE
todos backend

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/tft-stellar#316]
- [x] vesting dashboard ui done

- [ ] tokenstat to adapt vested tokens #289 

backend implementation
- [x] fix UI dashboard issues

- [ ] publish stellar metadata

- [x] need VM ?

- [x] deploy / host dashboard UI

**Comment by robvanmieghem** [comment]
Showing stellar metadat would be a good UI improvement for the dashboard, it is already publicly visible anyway.

**Comment by robvanmieghem** [comment]
No need for a VM, already deployed on the ha cluster, backup of the data is still neded, there is an issue for thatL #334

**Comment by robvanmieghem** [comment]
There is already an issue for adapting the tokenstats: #289

**Comment by robvanmieghem** [comment]
Just as a side note, I rather hjave the todo's in the projects as issues instead of creating combining new issues
