### ISSUE TITLE
invalid addresses show object object

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/tft-stellar#332]
![photo_2021-03-26_19-04-55](https://user-images.githubusercontent.com/43240801/112674400-2eeca080-8e66-11eb-890f-5e8ed39c4012.jpg)

**Comment by robvanmieghem** [comment]
TODO:
- [ ] The vesting service should catch the stellar_sdk exception and raise a j...exceptions.NotFound exception
- [] Properly show this error in the vesting dashboard

**Comment by ranatrk** [comment]
@robvanmieghem , Depending on the error, It can be shown briefly as `Address not found or Invalid Address not valid` to the user, while the stack trace is logged in the shell. Shouldnt these error messages be enough to the user to know what the issue is?
>     * [ ]  Properly show this error in the vesting dashboard
