### ISSUE TITLE
vesting dashboard front end and UI tweaks

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/tft-stellar#338]
- [ ] need a headline for the website, middle, before the image: **TFT Vesting Portal** 

- [ ] resize the image 80%

- [ ] change the favicon from vue logo to tflogo, new favicon: 
[favicon.png.zip](https://github.com/threefoldfoundation/tft-stellar/files/6236399/favicon.png.zip)

![image](https://user-images.githubusercontent.com/61866569/113098946-3d421000-920a-11eb-86af-e1c9afee35c8.png)

- [ ] Change "Owner Account Address" to be "Insert your TFT Wallet Address"

- [ ]  below 'address is required, add:
"The vested tokens will be returned to your wallet according to these specifications"

- [ ] auto-refresh dashboard when after new transaction added

- [ ] on bottom page middle, add "© 2021 [ThreeFold Foundation](https://new.threefold.io/). All rights reserved."

**Comment by maximilianrang** [comment]
Below the vesting adress, we need to add the following line:

"The vested tokens will be returned to your wallet according to these specifications"

**Comment by maximilianrang** [comment]
The favicon needs to be updated to TF Logo.
The mousover for the favicon needs to be changed from "frontend" to "TFT Vesting Portal"

**Comment by robvanmieghem** [comment]
@maximilianrang for "The vested tokens will be returned to your wallet according to these specifications"
Can you provide us with the link to the wiki where they are found?

**Comment by maximilianrang** [comment]
Clarified with @robvanmieghem directly. Please diregard my related comment above.

**Comment by DylanVerstraete** [comment]
![Screenshot from 2021-04-01 08-58-40](https://user-images.githubusercontent.com/17138347/113255747-7ccf3180-92c8-11eb-8455-8423e1720fbf.png)

**Comment by sasha-astiadi** [comment]
thank you @DylanVerstraete
