### ISSUE TITLE
fundPayment: transaction: 'tx_bad_auth_extra'

### ISSUE THREAD

**Issue by JonasWijne** [threefoldfoundation/tft-stellar#34]
When submitting a transaction funded by the `transactionfunding_service/fund_transaction`, i get the error `tx_bad_auth_extra`.

---

**Steps (all based on testnet) :**

1. create transaction
2. send xdr to transactionfunding_service/fund_transaction
3. sign response
4. submit signed response transaction

---
**Secret**
`SCXO52KWQKJET26HXRZXSLPFHBZHXEJU3QP4NGOD37NLMY4A6CXT6VXL`

**Transaction**
``` 
AAAAAD2h2A0COqDjaUtY+uHqR0FkLfq0Jpp7cNpqej5C9j4AAAAAAAAIvigAAAAEAAAAAQAAAAAAAAAAAAAAAF5nYgAAAAABAAAABHRlc3QAAAABAAAAAAAAAAEAAAAAw580zn0ZTa98Dd4KtE0
VhjwZzi7pCqVaprnWjEjWc2AAAAABVEZUAAAAAAA5/GQbeotMseuGw9LomxJQHv5mNT8nihPVgEwpv/efZAAAAAAAmJaAAAAAAAAAAAA=
```
**Response of fund transaction**
```
AAAAAPtuYYcHSePwQG9B2JLubqMnB6w2CTLgZNqutlw890LTAAAAZAAHG2gAAAAEAAAAAQAAAAAAAAAAAAAAAF5nYgAAAAABAAAABHRlc3QAAAABAAAAAAAAAAEAAAAAw580zn0ZTa98Dd4KtE0VhjwZzi7pCqVaprnWjEjWc2AAAAABVEZUAAAAAAA5/GQbeotMseuGw9LomxJQHv5mNT8nihPVgEwpv/efZAAAAAAAmJaAAAAAAAAAAAE890LTAAAAQNh/YU0kqzchceemGezCMBe+Q8zNVRm+qs0X+7kP2Nt0odkIkl8EyPwnFLt63k9uTSKyCbO79Ap6RIFAgHbWQAo=
```

**Comment by robvanmieghem** [comment]
The problem is that the sent transaction has set the sourceaccount on the transaction but not on the operation. The funding service replaces the source account of the transaction to fund it. Of course, since the operation has no source account, there is no signature for that operation.
