### ISSUE TITLE
New account creation appears to be timing out. ( Horizon stellar issue? )

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/tft-stellar#347]
- Currently new account creations are failing
- It seems there is a timeout on the actual stellar horizon APIs.

@robvanmieghem will also check if there's enough XLM to be sure, but it seems there is a timeout happening on a higher level right now.

**Comment by robvanmieghem** [comment]
Created a script to check the available XLM but that seems fine

**Comment by robvanmieghem** [comment]
There were indeed problems with the stellar horizon servers. Saw that new accounts have already been funded.
