### ISSUE TITLE
How to check whether a tfchain wallet has been converted into Stellar account

### ISSUE THREAD

**Issue by gmachtel** [threefoldfoundation/tft-stellar#38]
Need for a service to see whether a convert token has happened.

**Comment by robvanmieghem** [comment]
The [stellar horizon api](https://www.stellar.org/developers/horizon/reference/endpoints/accounts-single.html) can be checked to find out the balance of an account. When opening a wallet, this needs to be done anyway, a 404 is returned when the account is not activated yet.
I think adding an extra database and service only complicates things unnecessary.

**Comment by DylanVerstraete** [comment]
Well actually this PR: https://github.com/threefoldfoundation/tft-stellar/pull/32
also fixes this. Because if you hit the API with you tfchain and stellar address and you receive the error: `Migration already executed for address` then you know the migration already happened.
