### ISSUE TITLE
April 2021 minting

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#386]

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay-apr-2021.txt](https://github.com/threefoldfoundation/tft-stellar/files/6426585/payouts_signed_by_nickolay-apr-2021.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/6427357/payouts_signed_by_ahmed.txt)

**Comment by weynandkuijpers** [comment]
All done

[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/6431733/payouts_signed_by_weynand.txt)
