### ISSUE TITLE
TokenStats API Update required

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/tft-stellar#387]
We have right now two API endpoits for token trackers:
https://statsdata.threefoldtoken.com/stellar_stats/api/total_unlocked_tft
https://statsdata.threefoldtoken.com/stellar_stats/api/total_tft

We have to modify total_unlocked_tft in accordance to "Total liquid tokens: [277,750,707]" that we show in our wikis: https://wiki.threefold.io/#/threefold__stats_token_overview_farmed
Or if total_unlocked_tft shows some other number, we need to add another endpoint specifcially to track total_liquid_tft

Not sure also what exactly number total_unlocked_tft API returns, because if we calculate numbers according to the wiki, total unlocked tft, even excluding foundation liquid tokens is another number

Thank you

**Comment by robvanmieghem** [comment]
We changed the service with some improvements.
Still need to update production but 
total unlocked =  total_tokens - total_locked_tokens - total_vested_tokens - total_illiquid_foundation_tokens

**Comment by robvanmieghem** [comment]
@nbabenko the new statistics service has been deployed on the test server: https://statsdata.testnet.threefold.io/

**Comment by robvanmieghem** [comment]
deployed to production

**Comment by nbabenko** [comment]
cool, thank you. Regarding the formula
_total unlocked = total_tokens - total_locked_tokens - total_vested_tokens - total_illiquid_foundation_tokens_
Right now API shows 194,155,627.0852648 
https://statsdata.threefoldtoken.com/stellar_stats/api/total_unlocked_tft

And if we calculate according to the wiki it will be:
800,885,834-46,979,271-385,109,175-100,462,126 = 268,335,262
https://wiki.threefold.io/#/threefold__stats_token_overview_farmed

Can you please check why is such difference?

**Comment by robvanmieghem** [comment]
@nbabenko This is the data we and the wiki is based upon: https://statsdata.threefold.io/stellar_stats/api/stats

**Comment by nbabenko** [comment]
Ok, I found why such difference. API and statsdata returns data only on TFT, and wiki counts TFT+TFTA

**Comment by nbabenko** [comment]
Submitted data to the coinmarketcap, waiting for their feedback.

**Comment by robvanmieghem** [comment]
@nbabenko It was your proposal to only include tft in that call

**Comment by nbabenko** [comment]
yes, looks fine for now, already started submitting it to different token trackers
