### ISSUE TITLE
activation service is not reachable?

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldfoundation/tft-stellar#39]
I cant reach the activation_service as specified here: https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/activation-service

![image](https://user-images.githubusercontent.com/7256303/76978536-1bdff000-6937-11ea-8856-82a28fd53fa0.png)

`curl -X POST 'https://testnet.threefold.io/threefoldfoundation/activation_service/create_activation_code?address=GA62DWANAI5KBY3JJNMPVYPKI5AWILP2WQTJU63Q3JVHUPSC6Y7AATEP' -H 'Host: testnet.threefold.io'`

**Comment by robvanmieghem** [comment]
fixed and deployed on testnet
