### ISSUE TITLE
Minting may 2021

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#395]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/6590177/payouts_signed_by_ahmed.txt)

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/6591724/payouts_signed_by_nayer.txt)

**Comment by nbabenko** [comment]
[Uploading payouts_signed_by_nickolay_may_2021.txt…]()

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay_may_2021.txt](https://github.com/threefoldfoundation/tft-stellar/files/6595635/payouts_signed_by_nickolay_may_2021.txt)

**Comment by weynandkuijpers** [comment]
Payouts signed.
[Uploading payouts_signed_by_weynand_may_2021.txt…]()
