### ISSUE TITLE
Activations in production failing.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/tft-stellar#396]
We are not 100% sure this is on the activation service end, but we investigated and couldn't find what else could be wrong.

**Response :**

400 error: 

{"error": "/explorer/hashes/01524afbdede8dc8592d52d649df106ce285c1bc9c475731922e6b0b1d8c98c0f3b89ca2c2ca12: GET: no content available (code: 204)"}

**Call :**

curl "https://tokenservices.threefold.io/threefoldfoundation/conversion_service/activate_account" ^
  -H "authority: tokenservices.threefold.io" ^
  -H "pragma: no-cache" ^
  -H "cache-control: no-cache" ^
  -H "accept: application/json, text/plain, */*" ^
  -H "user-agent: Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1" ^
  -H "content-type: application/json;charset=UTF-8" ^
  -H "origin: https://wallet-beta.jimber.org" ^
  -H "sec-fetch-site: cross-site" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-dest: empty" ^
  -H "referer: https://wallet-beta.jimber.org/" ^
  -H "accept-language: en-US,en;q=0.9" ^
  --data-raw "^{^\^"args^\^":^{^\^"tfchain_address^\^":^\^"01524afbdede8dc8592d52d649df106ce285c1bc9c475731922e6b0b1d8c98c0f3b89ca2c2ca12^\^",^\^"address^\^":^\^"GCZPUBYIQKV6JJW7JU3GUW6M4YZN7GWN7LHO74SMXTUPQEPIU4ZZXMHV^\^"^}^}" ^
  --compressed

**Comment by robvanmieghem** [comment]
This is a conversion from a tfchain address, not a normal activation.

**Comment by ken-de-moor** [comment]
@robvanmieghem I probably linked the wrong call then. It seems to first try this , then go on to new one.

Here are the next calls in the chain.

curl "https://tokenservices.threefold.io/threefoldfoundation/activation_service/activate_account" ^
  -H "authority: tokenservices.threefold.io" ^
  -H "pragma: no-cache" ^
  -H "cache-control: no-cache" ^
  -H "accept: application/json, text/plain, */*" ^
  -H "user-agent: Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1" ^
  -H "content-type: application/json;charset=UTF-8" ^
  -H "origin: https://wallet-beta.jimber.org" ^
  -H "sec-fetch-site: cross-site" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-dest: empty" ^
  -H "referer: https://wallet-beta.jimber.org/" ^
  -H "accept-language: en-US,en;q=0.9" ^
  --data-raw "^{^\^"address^\^":^\^"GCZPUBYIQKV6JJW7JU3GUW6M4YZN7GWN7LHO74SMXTUPQEPIU4ZZXMHV^\^"^}" ^
  --compressed
  
  **Response (200 OK)** : 
"{\"activation_transaction\": \"AAAAAgAAAACUs1jkxPVfbOLVRpiOxMbN3mJHO9wPQ2cD4UMDrsjtlQAAAZABwCaHAABXSgAAAAEAAAAAAAAAAAAAAABgw2PLAAAAAAAAAAQAAAAAAAAAEAAAAACy+gcIgqvkpt9NNmpbzOYy35rN+s7v8ky86PgR6KczmwAAAAAAAAAAAAAAALL6BwiCq+Sm3002alvM5jLfms36zu/yTLzo+BHopzObAAAAAAAAAAAAAAABAAAAALL6BwiCq+Sm3002alvM5jLfms36zu/yTLzo+BHopzObAAAABgAAAAFURlQAAAAAAF1YKTg94x2O/muvqMcFiKjJAGYZJTG0I5eEOqzVJKMwf/////////8AAAABAAAAALL6BwiCq+Sm3002alvM5jLfms36zu/yTLzo+BHopzObAAAAEQAAAAAAAAABrsjtlQAAAEA+D2D66c6YBVN/E7rFHaxYVMRtzuHj70n1bung7e/lpeacxsxC9sR8XrOssvFbGQ197M4kowKetRyXQznegbQJ\", \"address\": \"GCZPUBYIQKV6JJW7JU3GUW6M4YZN7GWN7LHO74SMXTUPQEPIU4ZZXMHV\"}"

-------------------------------------

curl "https://horizon.stellar.org/transactions" ^
  -H "Connection: keep-alive" ^
  -H "Pragma: no-cache" ^
  -H "Cache-Control: no-cache" ^
  -H "Accept: application/json, text/plain, */*" ^
  -H "X-Client-Version: 8.2.2" ^
  -H "X-Client-Name: js-stellar-sdk" ^
  -H "User-Agent: Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1" ^
  -H "Content-Type: application/x-www-form-urlencoded" ^
  -H "Origin: https://wallet-beta.jimber.org" ^
  -H "Sec-Fetch-Site: cross-site" ^
  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Dest: empty" ^
  -H "Referer: https://wallet-beta.jimber.org/" ^
  -H "Accept-Language: en-US,en;q=0.9" ^
  --data-raw "tx=AAAAAgAAAACUs1jkxPVfbOLVRpiOxMbN3mJHO9wPQ2cD4UMDrsjtlQAAAZABwCaHAABXSgAAAAEAAAAAAAAAAAAAAABgw2PLAAAAAAAAAAQAAAAAAAAAEAAAAACy^%^2BgcIgqvkpt9NNmpbzOYy35rN^%^2Bs7v8ky86PgR6KczmwAAAAAAAAAAAAAAALL6BwiCq^%^2BSm3002alvM5jLfms36zu^%^2FyTLzo^%^2BBHopzObAAAAAAAAAAAAAAABAAAAALL6BwiCq^%^2BSm3002alvM5jLfms36zu^%^2FyTLzo^%^2BBHopzObAAAABgAAAAFURlQAAAAAAF1YKTg94x2O^%^2FmuvqMcFiKjJAGYZJTG0I5eEOqzVJKMwf^%^2F^%^2F^%^2F^%^2F^%^2F^%^2F^%^2F^%^2F^%^2F8AAAABAAAAALL6BwiCq^%^2BSm3002alvM5jLfms36zu^%^2FyTLzo^%^2BBHopzObAAAAEQAAAAAAAAACrsjtlQAAAEA^%^2BD2D66c6YBVN^%^2FE7rFHaxYVMRtzuHj70n1bung7e^%^2FlpeacxsxC9sR8XrOssvFbGQ197M4kowKetRyXQznegbQJ6KczmwAAAEByHnz6ctpHV6JwZMzWY0vhBOu4RBGcimza5bMxGRqXPe3Q1i2sIDsV4LyfAVLsrNA1mrEKUJwRBqCob8owkPMP" ^
  --compressed
  
  Response ( 400 bad request ) : 
  
  {
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/guides/concepts/list-of-operations.html",
  "extras": {
    "envelope_xdr": "AAAAAgAAAACUs1jkxPVfbOLVRpiOxMbN3mJHO9wPQ2cD4UMDrsjtlQAAAZABwCaHAABXSgAAAAEAAAAAAAAAAAAAAABgw2PLAAAAAAAAAAQAAAAAAAAAEAAAAACy+gcIgqvkpt9NNmpbzOYy35rN+s7v8ky86PgR6KczmwAAAAAAAAAAAAAAALL6BwiCq+Sm3002alvM5jLfms36zu/yTLzo+BHopzObAAAAAAAAAAAAAAABAAAAALL6BwiCq+Sm3002alvM5jLfms36zu/yTLzo+BHopzObAAAABgAAAAFURlQAAAAAAF1YKTg94x2O/muvqMcFiKjJAGYZJTG0I5eEOqzVJKMwf/////////8AAAABAAAAALL6BwiCq+Sm3002alvM5jLfms36zu/yTLzo+BHopzObAAAAEQAAAAAAAAACrsjtlQAAAEA+D2D66c6YBVN/E7rFHaxYVMRtzuHj70n1bung7e/lpeacxsxC9sR8XrOssvFbGQ197M4kowKetRyXQznegbQJ6KczmwAAAEByHnz6ctpHV6JwZMzWY0vhBOu4RBGcimza5bMxGRqXPe3Q1i2sIDsV4LyfAVLsrNA1mrEKUJwRBqCob8owkPMP",
    "result_codes": {
      "transaction": "tx_failed",
      "operations": [
        "op_success",
        "op_low_reserve",
        "op_no_source_account",
        "op_no_source_account"
      ]
    },
    "result_xdr": "AAAAAAAAAZD/////AAAABAAAAAAAAAAQAAAAAAAAAAAAAAAA/////f////7////+AAAAAA=="
  }
}

**Comment by ken-de-moor** [comment]
Confirmed fixed

**Comment by robvanmieghem** [comment]
Follow up issue for better monitoring: Monitor activation wallet #397
