### ISSUE TITLE
Test tokens needed after testnet reset.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/tft-stellar#403]
Could use some TFT and TFTA for testing since testnet reset again. Maybe 1 billion of each again? FreeTFT could also help but not 100% required as we don't fully support it anymore (but could be useful to validate it doesn't break stuff).

Trustlines are created already.

Address : GA35R3YMKOY2NQ3TUQQQPWU5KWZJVPOXFLUMLY7FMC7VYGWGU4H6VLBZ

**Comment by robvanmieghem** [comment]
done, 1 billion of each
