### ISSUE TITLE
June2021 Minting

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#405]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/6769282/payouts_signed_by_ahmed.txt)

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer_Jun_21.txt](https://github.com/threefoldfoundation/tft-stellar/files/6769355/payouts_signed_by_nayer_Jun_21.txt)

**Comment by weynandkuijpers** [comment]
All done and signed.

[payouts_signed_by_weynand_Jun_21.txt](https://github.com/threefoldfoundation/tft-stellar/files/6769454/payouts_signed_by_weynand_Jun_21.txt)

**Comment by maximilianrang** [comment]
[payouts_signed_by_max.txt](https://github.com/threefoldfoundation/tft-stellar/files/6770298/payouts_signed_by_max.txt)
