### ISSUE TITLE
minting July 2021

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#407]

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/6914904/payouts_signed_by_nayer.txt)

**Comment by maximilianrang** [comment]
[payouts_signed_by_maximilian.txt](https://github.com/threefoldfoundation/tft-stellar/files/6915173/payouts_signed_by_maximilian.txt)

**Comment by xmonader** [comment]
[payout_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/6918093/payout_signed_by_ahmed.txt)

**Comment by weynandkuijpers** [comment]
[payout_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/6918201/payout_signed_by_weynand.txt)
