### ISSUE TITLE
TF Connect - Retrieve TFT

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/tft-stellar#409]
Description: 
I've lost my phone and my seed phrase for TF Connect. 
I have a vested wallet with > 680k tft. 

3BOT name: alex24.3bot
email address: alex.hannelas@gmail.com
Vested wallet address: GD2T5BQQQZYJLIRQXENZBRLQL3BCG24G7R6XHQXX2M766QUTRXLLPMG5

Can we retrieve the seed phrase? 
If not, can we transfer the tft from the vested wallet address to a new tf connect wallet address?

**Comment by robvanmieghem** [comment]
Vesting wallet addresses need a signature weight of 10. There are 9 guardian signers with a weight of 1 and the owner that has a weight of 5. This means that the owner always has to cosign together with a majority of the guardians. This means the guardians can not do anything to the vested tokens without the signature of the owner,
