### ISSUE TITLE
minting August 2021

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#410]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/7097698/payouts_signed_by_ahmed.txt)

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/7097725/payouts_signed_by_nayer.txt)

**Comment by weynandkuijpers** [comment]
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/7097883/payouts_signed_by_weynand.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/7098577/payouts_signed_by_nickolay.txt)
