### ISSUE TITLE
September 2021 minting

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#413]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/7271143/payouts_signed_by_ahmed.txt)

**Comment by weynandkuijpers** [comment]
[signed_by_WeynanD.txt](https://github.com/threefoldfoundation/tft-stellar/files/7271162/signed_by_WeynanD.txt)

**Comment by Nayer-Sobhy** [comment]
[signed_by_WeynanD.txt](https://github.com/threefoldfoundation/tft-stellar/files/7271169/signed_by_WeynanD.txt)

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/7271170/payouts_signed_by_nayer.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/7273257/payouts_signed_by_nickolay.txt)
