### ISSUE TITLE
minting October 2021

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#414]

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/7465751/payouts_signed_by_nickolay.txt)

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/7465823/payouts_signed_by_nayer.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/7465839/payouts_signed_by_ahmed.txt)

**Comment by weynandkuijpers** [comment]
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/7466155/payouts_signed_by_weynand.txt)
