### ISSUE TITLE
minting november 2021

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#415]

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/7644867/payouts_signed_by_nayer.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/7644895/payouts_signed_by_ahmed.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/7645323/payouts_signed_by_nickolay.txt)

**Comment by weynandkuijpers** [comment]
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/7647465/payouts_signed_by_weynand.txt)
