### ISSUE TITLE
v2 minting December 2021

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#416]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/7816657/payouts_signed_by_ahmed.txt)

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/7816717/payouts_signed_by_nayer.txt)

**Comment by weynandkuijpers** [comment]
[payout_signed_by_weynand_new.txt](https://github.com/threefoldfoundation/tft-stellar/files/7819668/payout_signed_by_weynand_new.txt)

```
~$ wc -l ./payout_signed_by_weynand_new.txt 
1849 ./payout_signed_by_weynand_new.txt
```

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/7820070/payouts_signed_by_nickolay.txt)
