### ISSUE TITLE
Stellar.toml not parsed by some clients

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/tft-stellar#417]
Previously, Stellar based TFT could be found on StellarTerm for adding a trustline or trading. Now it doesn't show up in search and TFT shows as an "unknown" asset when connecting a wallet that already has a trustline. Reviewing some other interfaces, results are mixed. StellarX also doesn't show TFT, while InterStellar does.

Checking [Stellar.expert](https://stellar.expert/explorer/public/asset/TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47), the organization metadata tab does not appear, as it does for an asset like [yXLM](https://stellar.expert/explorer/public/asset/yXLM-GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55).

Our Stellar.toml file is in the correct location and appears to contain valid data. I found [this checker](https://stellar.sui.li/) which suggests the CORS might be an issue: `Your CORS header is not set. You have to set it to * to allow access to every client.`

Since the clients which do recognize TFT right now don't seem to have working Ledger support in my tests, resolving this is key to onboarding new Ledger users to TFT.

**Comment by scottyeager** [comment]
I see setting CORS was mentioned in #1. Probably this got overlooked in some website migration/reboot. @robvanmieghem, are you able to make this change or loop in someone who can?

**Comment by robvanmieghem** [comment]
The cors headers are indeed not present ( again).

**Comment by robvanmieghem** [comment]
It's solved again

**Comment by scottyeager** [comment]
Thanks @robvanmieghem. TFT appears on StellarTerm again and metadata is loaded by Stellar.expert.
