### ISSUE TITLE
v3 minting december 2021

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#419]

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/7869295/payouts_signed_by_nickolay.txt)
mykolababenko@Mykolas-MacBook-Air js-sdk % wc -l payouts_signed_by_nickolay.txt                                
      91 payouts_signed_by_nickolay.txt

**Comment by weynandkuijpers** [comment]
[payout_signed_by_weynand_v3.txt](https://github.com/threefoldfoundation/tft-stellar/files/7869444/payout_signed_by_weynand_v3.txt)
```
~$ wc -l payout_signed_by_weynand_v3.txt 
91 payout_signed_by_weynand_v3.txt
```

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/7870058/payouts_signed_by_ahmed.txt)

```
(.venv) ➜  minting wc -l *
    92 newsign.py
    91 payout_signed_by_weynand_v3.out
    91 payouts_signed_by_ahmed.txt
   274 total
 ```
