### ISSUE TITLE
Modify list of special wallets

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/tft-stellar#423]
Our list of special wallets is outdated (https://library.threefold.me/info/threefold#/tokens/threefold__stats_special_wallets)

We have to

- [x] Add "GDIJY6K2BBRIRX423ZFUYKKFDN66XP2KMSBZFQSE2PSNDZ6EDVQTRLSU" - "ThreeFold Carbon Credit Funding" under "Threefold Contribution Wallets" section.
- [x] Rename "GA7OPN4A3JNHLPHPEWM4PJDOYYDYNZOM7ES6YL3O7NC3PRY3V3UX6ANM" from "Liquid Exchange (foundation deposit)" to "Liquid Exchange # 1"
- [x] Delete "GCBFRQU4CR6K…	Liquid Aggregated Wallet" 
- [x] Add "GDSKFYNMZWTB3V5AN26CEAQ27643Q3KB4X6MY4UTO2LIIDFND4SPQZYU" - "Liquid Exchange # 2" under "Liquidity Wallets" section.
- [x] Delete "GAWOGIOPVKMWKYJHAMJCFPVOFAE44DEEZP3KALR4MCCZ2X35YRHIJTLR" (BTC-Alpha Exchange (foundation’s deposit is 200k)
- [x] Add "GBTPAXXP6534UPC4MLNGFGJWCD6DNSRVIPPOZWXAQAWI4FKTLOJY2A2S" "BTC-Alpha Exchange" under "Liquidity Wallets" section.
- [x] Add "GBQHN7RL4LSRPR2TT74ID2UJPZ2AXCHQY2WKGCTDLJM3NXVJ7GQHUCOD" "Gettft.com" under "Liquidity Wallets" section.
- [x] Delete "GBB6KRI2N55DOKYPLSGZ3TXJHZFLLHKXSKDCBJBOMAZK3MRAQA2Q4YND" "MAZRAA_TFT_MAIN TFT"
- [x] Delete "GD4OI4VVLWZQ…	Liquid Exchange"

**Comment by nbabenko** [comment]
Hello @robvanmieghem , can you please let me know when it is planned to be implemented?

**Comment by robvanmieghem** [comment]
@nbabenko  Are the tokens on the "ThreeFold Carbon Credit Funding" locked or liquid (free)?

**Comment by gmachtel** [comment]
It should be liquid, but I wonder whether it's to be considered as a TF controlled wallet. As these tokens will be sent to organisations such as TAG, to fund the green activities with (tree planting, ...)

**Comment by robvanmieghem** [comment]
@gmachtel So in the statistics they are liquid even when they are on this account and not sent to those organisations yet?

**Comment by gmachtel** [comment]
I believe so, @nbabenko please confirm.

**Comment by robvanmieghem** [comment]
Modified in the statistics service deployment. I assume there is some caching in the wiki.
