### ISSUE TITLE
V2 minting February 2022

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#426]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/8187423/payouts_signed_by_ahmed.txt)

```
(.venv) ➜  minting wc -l *
   2033 payouts_signed_by_ahmed.txt
   2033 v2_payouts_to_sign.txt

```

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/8187911/payouts_signed_by_nickolay.txt)

wc -l payouts_signed_by_nickolay.txt                                
    2033 payouts_signed_by_nickolay.txt

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/8187978/payouts_signed_by_nayer.txt)

**Comment by weynandkuijpers** [comment]
[payouts_signed_by_weynand_february.txt](https://github.com/threefoldfoundation/tft-stellar/files/8190347/payouts_signed_by_weynand_february.txt)
```
➜  february wc -l payouts_signed_by_nayer-february.txt 
2033 payouts_signed_by_nayer-february.txt
➜  february wc -l payouts_signed_by_weynand_february.txt 
2033 payouts_signed_by_weynand_february.txt
➜  february 
```
