### ISSUE TITLE
February 2022 minting correction

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#428]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/8326248/payouts_signed_by_ahmed.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/8327343/payouts_signed_by_nickolay.txt)

**Comment by weynandkuijpers** [comment]
Done
```
➜  tmp cat payouts_signed_by_weynand.txt| wc -l
     608
➜  tmp
```
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/8329339/payouts_signed_by_weynand.txt)
