### ISSUE TITLE
March 2022 testnet minting

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#430]

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/8588387/payouts_signed_by_nayer.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/8601693/payouts_signed_by_nickolay.txt)
ykolababenko@Mykolas-MacBook-Air js-sdk % wc -l payouts_signed_by_nickolay.txt                            
      43 payouts_signed_by_nickolay.txt

**Comment by weynandkuijpers** [comment]
```
➜  tmp wc -l /tmp/payouts_singed_by_weynand.txt
      43 /tmp/payouts_singed_by_weynand.txt
```
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/8602091/payouts_signed_by_weynand.txt)
