### ISSUE TITLE
User is saying his tokens of the last 2 months have not unlocked

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tft-stellar#431]
Grootzande.3bot
GCPFF2JYUXW5WYSVSZRIOM3NGQQ7TSKHPN6K7GKGZIL5CHGPU6NTBSG5

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/tft-stellar/blob/master/docs/faq.md#how-do-i-check-the-timelocked-tokens-of-an-account

https://statsdata.threefoldtoken.com/stellar_stats/api/account/GCPFF2JYUXW5WYSVSZRIOM3NGQQ7TSKHPN6K7GKGZIL5CHGPU6NTBSG5

**Comment by sabrinasadik** [comment]
According to this it in fact did not unlock, how is that possible?

**Comment by robvanmieghem** [comment]
wallet issue, not an issue for this repo
