### ISSUE TITLE
Minting testnet v3 April 2022

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#433]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/8798107/payouts_signed_by_ahmed.txt)

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/8798408/payouts_signed_by_nayer.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/8798533/payouts_signed_by_nickolay.txt)

**Comment by weynandkuijpers** [comment]
```
➜  tmp cat payouts_signed_by_nickolay.txt | wc -l
      42
➜  tmp cat payouts_signed_by_weynand.txt| wc -l
      42
➜  tmp
```
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/8798803/payouts_signed_by_weynand.txt)
