### ISSUE TITLE
Minting June 2022

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#440]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/9043657/payouts_signed_by_ahmed.txt)

```
     92 newsign.py
   3431 payouts_signed_by_ahmed.txt
   3431 payouts_to_sign.txt
   6954 total

```

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/9043835/payouts_signed_by_nayer.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/9043964/payouts_signed_by_nickolay.txt)
js-sdk % wc -l payouts_signed_by_nickolay.txt                                
    3431 payouts_signed_by_nickolay.txt

**Comment by weynandkuijpers** [comment]
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/9044559/payouts_signed_by_weynand.txt)

```
➜  tmp wc -l payouts_signed_by_*
    3431 payouts_signed_by_nickolay.txt
    3431 payouts_signed_by_weynand.txt
    6862 total
    ```
