### ISSUE TITLE
Minting July 2022

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#441]

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/9261093/payouts_signed_by_nickolay.txt)
js-sdk % wc -l payouts_signed_by_nickolay.txt                        
    3770 payouts_signed_by_nickolay.txt

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/9267893/payouts_signed_by_ahmed.txt)

```
~>  wc  -l *
     92 newsign.py
   3770 payouts_signed_by_ahmed.txt
   3770 payouts_to_sign.txt
     71 sign.py
   7703 total

```

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/9268036/payouts_signed_by_nayer.txt)

wc -l payouts_signed_by_ahmed.txt payouts_signed_by_nayer.txt 
   3770 payouts_signed_by_ahmed.txt
   3770 payouts_signed_by_nayer.txt
   7540 total

**Comment by weynandkuijpers** [comment]
```
➜  tmp wc -l payouts.txt new_signed_by_weynand.txt
    3770 payouts.txt
    3770 new_signed_by_weynand.txt
    7540 total
 ```
[new_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/9274524/new_signed_by_weynand.txt)
