### ISSUE TITLE
Minting August 2022

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#444]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/9499267/payouts_signed_by_ahmed.txt)

``` ~> wc -l 
   3341 payouts_signed_by_ahmed.txt
   3341 payouts_to_sign.txt

```

**Comment by Nayer-Sobhy** [comment]
3341 payouts_signed_by_ahmed.txt
    3341 payouts_signed_by_nayer.txt
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/9502874/payouts_signed_by_nayer.txt)

    6682 total

**Comment by weynandkuijpers** [comment]
Done.
[august_payouts_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/9503281/august_payouts_weynand.txt)

```
(js-sdk-wPTt9d3q-py3.9) johndoe@signing:~/opt/js-sdk/signed/202209$ wc -l *
   3341 august_payouts_weynand.txt
   3341 payouts_signed_by_nayer.txt
```

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/9503967/payouts_signed_by_nickolay.txt)

js-sdk % wc -l payouts_signed_by_nickolay.txt                               
    3341 payouts_signed_by_nickolay.txt
