### ISSUE TITLE
Check stellar.toml

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#446]
The stellar.toml seems to be missing some fields. For instance, on stellar.expert (https://stellar.expert/explorer/public/asset/TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1), when checking the TFT curreny, it gives a warning about the DOCUMENTATION section. It also complains about not finding the images. The same warning is repeated on the page of the issuer account.

![image](https://user-images.githubusercontent.com/22023708/191708277-bfff0cb7-1ae1-4167-85c9-68eb7a0924a2.png)

**Comment by robvanmieghem** [comment]
TODO: 
- #447 
- #448
