### ISSUE TITLE
Minting September 2022

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#449]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/9751717/payouts_signed_by_ahmed.txt)

``` ~> wc -l *
   3696 payouts_signed_by_ahmed.txt
   3696 payouts_to_sign.txt
```

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/9751963/payouts_signed_by_nayer.txt)

3696 payouts_signed_by_ahmed.txt
    3696 payouts_signed_by_nayer.txt

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/9753754/payouts_signed_by_nickolay.txt)

wc -l payouts_signed_by_nickolay.txt
    3696 payouts_signed_by_nickolay.txt

**Comment by weynandkuijpers** [comment]
```
➜  ~ wc -l payouts_signed_by_weynand.txt
    3696 payouts_signed_by_weynand.txt
```
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/9757598/payouts_signed_by_weynand.txt)
