### ISSUE TITLE
Update services to the newest js-sdk without explorer v2 dependency

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/tft-stellar#451]
- [ ] tftservices
- [x] tftstatistics
    - [x] #457

**Comment by xmonader** [comment]
@abom please make sure to add the tag here to know to which version of sdk we should upgrade too, then rob can start testing

**Comment by abom** [comment]
Latest version with newest stellar-sdk too

https://github.com/threefoldtech/js-sdk/releases/tag/v11.5-b15

**Comment by robvanmieghem** [comment]
made a pre-release v1.4.13-a, published to the helm repo, will deploy it to the test environment

**Comment by robvanmieghem** [comment]
deployed to test environment

**Comment by robvanmieghem** [comment]
Bugs:
 - [ ] [Stellar client add_trustline crashes](https://github.com/threefoldtech/js-sdk/issues/3385)

**Comment by abom** [comment]
A new release with the bug fix of @robvanmieghem 

https://github.com/threefoldtech/js-sdk/releases/tag/v11.5-b16

**Comment by robvanmieghem** [comment]
upgraded testenvironment to v.4.13-a2 with js-sdk v11.5-b16

**Comment by robvanmieghem** [comment]
bugs ( for tftstatistics):

- [ ] js-sdk: [stellar client getbalance with timelocked tokens crashes](https://github.com/threefoldtech/js-sdk/issues/3388)

**Comment by robvanmieghem** [comment]
published a new release for the statistics service

**Comment by robvanmieghem** [comment]
deployed the statistics service to production

**Comment by robvanmieghem** [comment]
tftservices to test:

- [ ] activationservice
- [ ] transactionfunding
- [ ] unlock service
- [ ] vesting

**Comment by robvanmieghem** [comment]
published release 1.4.13
