### ISSUE TITLE
Minting October 2022

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#455]

**Comment by weynandkuijpers** [comment]
Unsigned starting file: 
[payouts_to_sign.txt](https://github.com/threefoldfoundation/tft-stellar/files/9936315/payouts_to_sign.txt)

**Comment by weynandkuijpers** [comment]
```
(js-sdk-wPTt9d3q-py3.9) weynandkuijpers@signing:~/opt/js-sdk/signed/202210$ wc -l *
   3156 payouts_signed_by_weynand.txt
   3156 payouts_to_sign.txt
   6312 total
   ```

[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/9936392/payouts_signed_by_weynand.txt)

**Comment by xmonader** [comment]
```
root@ba07091e6bde:/minting# wc -l *
     92 newsign.py
   3156 payouts_signed_by_ahmed.txt
   3156 payouts_signed_by_weynand.txt
   6404 total

```
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/9937179/payouts_signed_by_ahmed.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/9937545/payouts_signed_by_nickolay.txt)

js-sdk % wc -l payouts_signed_by_nickolay.txt                                       
    3156 payouts_signed_by_nickolay.txt

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/9943224/payouts_signed_by_nayer.txt)
# wc -l *
     92 newsign.py
   3156 payouts_signed_by_nayer.txt
   3156 payouts_signed_by_nickolay.txt
