### ISSUE TITLE
Minting November 2022

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#465]

**Comment by xmonader** [comment]
```
root@f78a69065dbd:/minting# wc -l *
     92 newsign.py
   3141 payouts_signed_by_ahmed.txt
   3141 payouts_to_sign.txt
   6374 total

```
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/10146106/payouts_signed_by_ahmed.txt)

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/10146256/payouts_signed_by_nayer.txt)

**Comment by weynandkuijpers** [comment]
Done
```
(js-sdk-wPTt9d3q-py3.9) johndoe@signing:~/opt/js-sdk$ wc -l payouts_signed_by_*
   3141 payouts_signed_by_nayer.txt
   3141 payouts_signed_by_weynand.txt
   6282 total
(js-sdk-wPTt9d3q-py3.9) johndoe@signing:~/opt/js-sdk$
```
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/10146437/payouts_signed_by_weynand.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/10146625/payouts_signed_by_nickolay.txt)

% wc -l payouts_signed_by_nickolay.txt                                        
    3141 payouts_signed_by_nickolay.txt
