### ISSUE TITLE
Minting December 2022

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#467]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/10337641/payouts_signed_by_ahmed.txt)

```
root@6dc12073c842:/minting# wc -l *
     92 newsign.py
   3230 payouts_signed_by_ahmed.txt
   3230 payouts_to_sign.txt
   6552 total
root@6dc12073c842:/minting# ls -lh
total 2.4M
-rw-rw-r-- 1 1000 1000 3.5K Nov  4 09:37 newsign.py
-rw-r--r-- 1 root root 1.4M Jan  3 15:05 payouts_signed_by_ahmed.txt
-rw-rw-r-- 1 1000 1000 1.1M Jan  3 14:52 payouts_to_sign.txt

```

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/10337690/payouts_signed_by_nickolay.txt)

 wc -l payouts_signed_by_nickolay.txt                                       
    3230 payouts_signed_by_nickolay.txt

**Comment by weynandkuijpers** [comment]
```
➜  tmp wc -l ./payouts_signed_by_*
    3230 ./payouts_signed_by_nickolay.txt
    3230 ./payouts_signed_by_weynand.txt
    6460 total
```
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/10338145/payouts_signed_by_weynand.txt)

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer (1).txt](https://github.com/threefoldfoundation/tft-stellar/files/10338626/payouts_signed_by_nayer.1.txt)
