### ISSUE TITLE
Minting January 2023

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#470]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/10569315/payouts_signed_by_ahmed.txt)

```
   3029 payouts_signed_by_ahmed.txt
   3029 payouts_to_sign.txt

```

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/10569608/payouts_signed_by_nayer.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/10570538/payouts_signed_by_nickolay.txt)
js-sdk % wc -l payouts_signed_by_nickolay.txt                                      
    3029 payouts_signed_by_nickolay.txt

**Comment by weynandkuijpers** [comment]
Done 
```
(js-sdk-wPTt9d3q-py3.9) johndoe@signing:~/opt/js-sdk$ wc -l ./payouts_signed_by_*
   3029 ./payouts_signed_by_nickolay.txt
   3029 ./payouts_signed_by_weynand.txt
   6058 total
```
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/10575763/payouts_signed_by_weynand.txt)
