### ISSUE TITLE
Minting February 2023

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#474]

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/10897626/payouts_signed_by_nayer.txt)
 2989 payouts_signed_by_nayer.txt
    2989 payouts_to_sign.txt

**Comment by nbabenko** [comment]
js-sdk % wc -l payouts_signed_by_nickolay.txt                                      
    2989 payouts_signed_by_nickolay.txt
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/10898421/payouts_signed_by_nickolay.txt)

**Comment by weynandkuijpers** [comment]
➜  tmp wc -l payouts_signed_by_*
    2989 payouts_signed_by_nickolay.txt
    2989 payouts_signed_by_weynand.txt
    5978 total

[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/10898692/payouts_signed_by_weynand.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/10899330/payouts_signed_by_ahmed.txt)
