### ISSUE TITLE
TFTA to TFT conversion incomplete

### ISSUE THREAD

**Issue by TullysInc** [threefoldfoundation/tft-stellar#494]
The user transfered 25,659.89TFTA to the issuer add: GBUT4GP5GJ6B3XW5PXENHQA7TXJI5GOPW3NF4W3ZIW6OOO4ISY6WNLN2 and hasn't yet received TFTs to his wallet address: GDZNVZGCSBMBTPQEI25AEGQVASPOIK6WZES6CIF4V6BKPDJUIU3P67Y4

https://stellar.expert/explorer/public/tx/195110928214253568#195110928214253570

![TFTA_TFT conversion](https://user-images.githubusercontent.com/105203696/228588903-4f0873e4-fe7f-46cb-8057-a8a5bbd18d6a.jpg)

**Comment by robvanmieghem** [comment]
solved: https://stellar.expert/explorer/public/tx/195872404441202688#195872404441202689

**Comment by TullysInc** [comment]
Thank you for the quick turnaround.
