### ISSUE TITLE
Minting April 2023

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#504]

**Comment by xmonader** [comment]
```
➜  minting wc -l *
     92 newsign.py
   2254 payouts_signed_by_ahmed.txt
   2254 payouts_signed_by_nayer.txt
```

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/11454440/payouts_signed_by_nickolay.txt)
js-sdk % wc -l payouts_signed_by_nickolay.txt 
    2254 payouts_signed_by_nickolay.txt

**Comment by weynandkuijpers** [comment]
Done.
```
➜  tmp wc -l payouts_signed_by_nickolay\ April\ 2023.txt payouts_signed_by_weynand_april_2023.txt
    2254 payouts_signed_by_nickolay April 2023.txt
    2254 payouts_signed_by_weynand_april_2023.txt
    4508 total
```

[payouts_signed_by_weynand_april_2023.txt](https://github.com/threefoldfoundation/tft-stellar/files/11459854/payouts_signed_by_weynand_april_2023.txt)
