### ISSUE TITLE
minting June 2023

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#508]

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/11971779/payouts_signed_by_nayer.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/11972128/payouts_signed_by_ahmed.txt)


```
➜  minting wc -l *
   2933 payouts_signed_by_ahmed.txt
   2933 payouts_signed_by_nayer.txt

```

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/11974778/payouts_signed_by_nickolay.txt)
% wc -l payouts_signed_by_nickolay.txt                                       
    2933 payouts_signed_by_nickolay.txt

**Comment by weynandkuijpers** [comment]
Done.

```
(js-sdk-wPTt9d3q-py3.9) johndoe@signing:~/opt/js-sdk$ wc -l payouts_signed*
   2933 payouts_signed.txt
   2933 payouts_signed_by_nickolay.txt
   5866 total
```
