### ISSUE TITLE
Minting june 2023 farmerbot fix

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#509]

**Comment by Nayer-Sobhy** [comment]
% wc -l payouts_signed_by_nayer.txt
     202 payouts_signed_by_nayer.txt
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/12073099/payouts_signed_by_nayer.txt)

**Comment by weynandkuijpers** [comment]
Done.

```
(js-sdk-wPTt9d3q-py3.9) johndoe@signing:~/opt/js-sdk$ wc -l ./payouts_signed_by_*
   202 ./payouts_signed_by_nayer.txt
   202 ./payouts_signed_by_weynand.txt
   404 total
```

[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/12076088/payouts_signed_by_weynand.txt)
