### ISSUE TITLE
Minting July 2023

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#510]

**Comment by weynandkuijpers** [comment]
[payouts_to_sign.txt](https://github.com/threefoldfoundation/tft-stellar/files/12266453/payouts_to_sign.txt)

Original file to sign

**Comment by weynandkuijpers** [comment]
(js-sdk-wPTt9d3q-py3.9) johndoe@signing:~/opt/js-sdk$ wc -l payouts_*
   2882 payouts_signed_by_weynand.txt
   2882 payouts_to_sign.txt
   5764 total
   
   
[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/12266469/payouts_signed_by_weynand.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/12267153/payouts_signed_by_nickolay.txt)
wc -l payouts_signed_by_nickolay.txt                               
    2882 payouts_signed_by_nickolay.txt

**Comment by Nayer-Sobhy** [comment]
2882 payouts_signed_by_nayer.txt
 
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/12267159/payouts_signed_by_nayer.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/12267169/payouts_signed_by_ahmed.txt)


```
(js-sdk-9TQBlLpp-py3.10) ➜  minting wc -l *
   2882 payouts_signed_by_ahmed.txt
   2882 payouts_signed_by_nayer.txt

```
