### ISSUE TITLE
Minting August 20223

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#512]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/12537025/payouts_signed_by_ahmed.txt)

```
(js-sdk-9TQBlLpp-py3.10) ➜  minting wc -l *
   2732 payouts_signed_by_ahmed.txt
   2732 payouts_to_sign.txt

```

**Comment by Nayer-Sobhy** [comment]
2732 payouts_signed_by_nayer.txt
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/12537476/payouts_signed_by_nayer.txt)

**Comment by weynandkuijpers** [comment]
```
(js-sdk-wPTt9d3q-py3.9) johndoe@signing:~/opt/js-sdk$ wc -l *.txt
   2732 payouts_signed_by_nayer.txt
   2732 payouts_signed_by_weynand.txt
   5464 total
```

[payouts_signed_by_weynand.txt](https://github.com/threefoldfoundation/tft-stellar/files/12537607/payouts_signed_by_weynand.txt)

**Comment by delandtj** [comment]
2732 [payouts_signed_by_jan.txt](https://github.com/threefoldfoundation/tft-stellar/files/12538051/payouts_signed_by_jan.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/12543753/payouts_signed_by_nickolay.txt)
wc -l payouts_signed_by_nickolay.txt
    2732 payouts_signed_by_nickolay.txt
