### ISSUE TITLE
Minting September 2023

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#513]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/12844244/payouts_signed_by_ahmed.txt)

**Comment by Nayer-Sobhy** [comment]
2609 payouts_signed_by_ahmed.txt
    2609 payouts_signed_by_nayer.txt
    
    
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/12844561/payouts_signed_by_nayer.txt)

**Comment by nbabenko** [comment]
wc -l payouts_signed_by_nickolay.txt                                     
    2609 payouts_signed_by_nickolay.txt

[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/12845040/payouts_signed_by_nickolay.txt)

**Comment by delandtj** [comment]
```wc -l payouts_signed_by_jan.txt
2609 payouts_signed_by_jan.txt```

[payouts_signed_by_jan.txt](https://github.com/threefoldfoundation/tft-stellar/files/12847530/payouts_signed_by_jan.txt)
