### ISSUE TITLE
Minting november 2023

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#515]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/13644216/payouts_signed_by_ahmed.txt)


```
➜  minting wc -l *
   2188 payouts_signed_by_ahmed.txt
   2188 payouts_to_sign.txt
```

**Comment by Nayer-Sobhy** [comment]
2188 payouts_signed_by_nayer.txt
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/13644404/payouts_signed_by_nayer.txt)

**Comment by nbabenko** [comment]
wc -l payouts_signed_by_nickolay.txt 
    2188 payouts_signed_by_nickolay
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/13649199/payouts_signed_by_nickolay.txt)
.txt

**Comment by delandtj** [comment]
[payouts_signed_by_jan.txt](https://github.com/threefoldfoundation/tft-stellar/files/13653286/payouts_signed_by_jan.txt)
```
wc -l payouts_signed_by_jan.txt
2188 payouts_signed_by_jan.txt
```
