### ISSUE TITLE
Minting February 2024

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#519]

**Comment by Nayer-Sobhy** [comment]
payouts_signed_by_nayer.txt
    2164 payouts_signed_by_nayer.txt
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/14486507/payouts_signed_by_nayer.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/14486527/payouts_signed_by_ahmed.txt)

```
(js-sdk-9TQBlLpp-py3.10) ➜  minting wc -l *    
   2164 payouts_signed_by_ahmed.txt
   2164 payouts_signed_by_nayer.txt

```

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/14497297/payouts_signed_by_nickolay.txt)

wc -l payouts_signed_by_nickolay.txt 
    2164 payouts_signed_by_nickolay.txt
