### ISSUE TITLE
TFTA conversions are delayed

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/tft-stellar#521]
Users trying to convert TFTA to TFT are sometimes experiencing long delays. Of the last three conversion attempts:

1. Took about 2 days
2. Was processed in a few minutes
3. Is still pending after 3 days

Quoting @robvanmieghem on another issue:

> Bitcoin keeps swinging very hard so this ripples through to all other blockchains because of all the defi.
So the Stellar chain is very loaded too increasing the transaction fee and causing timeouts.
The conversion service is quite old code not capable of dealing with that properly. I'll restart it so these transactions are picked up again.

Let's figure out what to do so that this service is reliable.

**Comment by robvanmieghem** [comment]
TFTA was a temporary token which is no longer used and has not been issued for years.
People were able to convert TFTA to TFT for years too and there is not much TFTA left.
The conversion is reliable, not a single TFTA to TFT conversio has not been able to be executed.
Yes, sometimes a support ticket was needed to restart the service to pick up the TFTA conversions with a failed TFT issuance.
I would not spend much effort in a problem that's getting smaller and smaller as almost no people have TFTA left.
