### ISSUE TITLE
Minting March 2024

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#522]

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/14890039/payouts_signed_by_ahmed.txt)

```
(js-sdk-9TQBlLpp-py3.10) ➜  minting wc -l *
   2372 payouts_signed_by_ahmed.txt
   2372 payouts_to_sign.txt

```

**Comment by Nayer-Sobhy** [comment]
2372 payouts_signed_by_nayer.txt
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/14892611/payouts_signed_by_nayer.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/14902169/payouts_signed_by_nickolay.txt)
wc -l payouts_signed_by_nickolay.txt
    2372 payouts_signed_by_nickolay.txt

**Comment by delandtj** [comment]
[payouts_signed_by_jan.txt](https://github.com/threefoldfoundation/tft-stellar/files/14902848/payouts_signed_by_jan.txt)
```
 ╭─delandtj@delandtj in repo: signer on  master [?] via  v1.22.2 as 🧙 took 3ms
 ╰─λ wc -l payouts_signed_by_jan.txt
2372 payouts_signed_by_jan.txt
```
