### ISSUE TITLE
Minting April 2024

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#523]

**Comment by delandtj** [comment]
File :
[payouts_signed_by_jan.txt](https://github.com/threefoldfoundation/tft-stellar/files/15220829/payouts_signed_by_jan.txt)


``` 
╭─delandtj@delandtj in repo: signer on  master [?] via  v1.22.2 as 🧙 took 2ms
 ╰─λ wc -l payouts_to_sign.txt
2529 payouts_to_sign.txt

 ╭─delandtj@delandtj in repo: signer on  master [?] via  v1.22.2 as 🧙 took 1ms
 ╰─λ wc -l payouts_signed_by_jan.txt
2529 payouts_signed_by_jan.txt`
``

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/threefoldfoundation/tft-stellar/files/15221701/payouts_signed_by_ahmed.txt)

```
➜  minting wc -l *
    2529 payouts_signed_by_ahmed.txt
    2529 payouts_signed_by_jan.txt

```

**Comment by nbabenko** [comment]
[Uploading payouts_signed_by_nickolay.txt…]()

wc -l payouts_signed_by_nickolay.txt 
    2529 payouts_signed_by_nickolay.txt

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/threefoldfoundation/tft-stellar/files/15224346/payouts_signed_by_nickolay.txt)

wc -l payouts_signed_by_nickolay.txt
2529 payouts_signed_by_nickolay.txt

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/threefoldfoundation/tft-stellar/files/15233195/payouts_signed_by_nayer.txt)

wc -l payouts_signed_by_nayer.txt 
    2529 payouts_signed_by_nayer.txt
