### ISSUE TITLE
Minting May 2024

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#524]

**Comment by Nayer-Sobhy** [comment]
wc -l payouts_signed_by_nayer.txt
    1897 payouts_signed_by_nayer.txt
[payouts_signed_by_nayer.txt](https://github.com/user-attachments/files/15760303/payouts_signed_by_nayer.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/user-attachments/files/15775099/payouts_signed_by_ahmed.txt)

```
➜  minting wc -l *
    1897 payouts_signed_by_ahmed.txt
    1897 payouts_signed_by_nayer.txt
```

**Comment by delandtj** [comment]
[payouts_signed_by_jan.txt](https://github.com/user-attachments/files/15791193/payouts_signed_by_jan.txt)

```
╭─delandtj@delandtj in repo: signer on  master [?] via  v1.22.4 as 🧙 took 58ms
╰─λ wc -l payouts_signed_by_jan.txt
1897 payouts_signed_by_jan.txt
```

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/user-attachments/files/15792274/payouts_signed_by_nickolay.txt)
wc -l payouts_signed_by_nickolay.txt 
    1897 payouts_signed_by_nickolay.txt
