### ISSUE TITLE
Minting June 2024

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#528]

**Comment by Nayer-Sobhy** [comment]
2483 payouts_signed_by_nayer.txt

[payouts_signed_by_nayer.txt](https://github.com/user-attachments/files/16140693/payouts_signed_by_nayer.txt)

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/user-attachments/files/16140741/payouts_signed_by_ahmed.txt)

```
➜  minting wc -l *
    2483 payouts_signed_by_ahmed
    2483 payouts_signed_by_nayer.txt

```

**Comment by delandtj** [comment]
[payouts_signed_by_jan.txt](https://github.com/user-attachments/files/16158120/payouts_signed_by_jan.txt)

```
 ╭─delandtj@delandtj in repo: signer on  master [?] via  v1.22.5 as 🧙 took 78ms
2483 payouts_signed_by_jan.txt
```

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/user-attachments/files/16158222/payouts_signed_by_nickolay.txt)
wc -l payouts_signed_by_nickolay.txt 
    2483 payouts_signed_by_nickolay.txt
