### ISSUE TITLE
Minting July 2024

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#529]

**Comment by delandtj** [comment]
```
 ╭─delandtj@delandtj in repo: signer on  master [x?] via  v1.22.5 as 🧙 took 49ms
 ╰─λ wc -l payouts_to_sign.txt
1607 payouts_to_sign.txt

 ╭─delandtj@delandtj in repo: signer on  master [x?] via  v1.22.5 as 🧙 took 1ms
 ╰─λ wc -l payouts_signed_by_jan.txt
1607 payouts_signed_by_jan.txt
```
[payouts_signed_by_jan.txt](https://github.com/user-attachments/files/16522282/payouts_signed_by_jan.txt)

**Comment by Nayer-Sobhy** [comment]
wc -l payouts_signed_by_nayer.txt 
    1607 payouts_signed_by_nayer.txt
[payouts_signed_by_nayer.txt](https://github.com/user-attachments/files/16522367/payouts_signed_by_nayer.txt)

**Comment by xmonader** [comment]
```
➜  minting wc -l *
    1607 payouts_signed_by_ahmed
    1607 payouts_signed_by_nayer.txt

```
[payouts_signed_by_ahmed.txt](https://github.com/user-attachments/files/16532715/payouts_signed_by_ahmed.txt)

**Comment by nbabenko** [comment]
[payouts_signed_by_nickolay.txt](https://github.com/user-attachments/files/16549513/payouts_signed_by_nickolay.txt)
wc -l payouts_signed_by_nickolay.txt 
    1607 payouts_signed_by_nickolay.txt

**Comment by ramezsaeed** [comment]
[payouts_signed_by_ramez.txt](https://github.com/user-attachments/files/16573397/payouts_signed_by_ramez.txt)
```
wc -l /home/ramez/Desktop/payouts_signed_by_ramez.txt 
1607 /home/ramez/Desktop/payouts_signed_by_ramez.txt
```
