### ISSUE TITLE
Minting August 2024

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#530]

**Comment by Nayer-Sobhy** [comment]
wc -l payouts_signed_by_nayer.txt 
    1882 payouts_signed_by_nayer.txt
[payouts_signed_by_nayer.txt](https://github.com/user-attachments/files/16931692/payouts_signed_by_nayer.txt)

**Comment by ramezsaeed** [comment]
wc -l payouts_signed_by_ramez.txt 
1882 payouts_signed_by_ramez.txt
[payouts_signed_by_ramez.txt](https://github.com/user-attachments/files/16932062/payouts_signed_by_ramez.txt)

**Comment by mik-tf** [comment]
wc -l payouts_signed_by_mik.txt
1882 payouts_signed_by_mik.txt
[payouts_signed_by_mik.txt](https://github.com/user-attachments/files/16932259/payouts_signed_by_mik.txt)

**Comment by delandtj** [comment]
[payouts_signed_by_jan.txt](https://github.com/user-attachments/files/16932341/payouts_signed_by_jan.txt)

```
 ╭─delandtj@delandtj in repo: signer on  master [x?] via  v1.23.1 as 🧙 took 66ms
 ╰─λ wc -l payouts_signed_by_jan.txt
1882 payouts_signed_by_jan.txt
```
