### ISSUE TITLE
Minting September 2024 

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#531]

**Comment by delandtj** [comment]
[payouts_signed_by_jan.txt](https://github.com/user-attachments/files/17258076/payouts_signed_by_jan.txt)

``` 
╭─delandtj@delandtj in repo: signer on  master [x?] via  v1.23.1 as 🧙 took 59ms
 ╰─λ wc -l payouts_to_sign.txt
1802 payouts_to_sign.txt

 ╭─delandtj@delandtj in repo: signer on  master [x?] via  v1.23.1 as 🧙 took 1ms
 ╰─λ wc -l payouts_signed_by_jan.txt
1802 payouts_signed_by_jan.txt
```

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/user-attachments/files/17258508/payouts_signed_by_ahmed.txt)


```
➜  minting wc -l *
    1802 payouts_signed_by_ahmed.txt
    1802 payouts_signed_by_jan.txt

```

**Comment by mik-tf** [comment]
[payouts_signed_by_mik.txt](https://github.com/user-attachments/files/17258617/payouts_signed_by_mik.txt)

```
wc -l payouts_*
   1802 payouts_signed_by_ahmed.txt
   1802 payouts_signed_by_mik.txt
   3604 total
```

**Comment by Nayer-Sobhy** [comment]
wc -l payouts_signed_by_nayer.txt
    1802 payouts_signed_by_nayer.txt
[payouts_signed_by_nayer.txt](https://github.com/user-attachments/files/17276085/payouts_signed_by_nayer.txt)
