### ISSUE TITLE
Minting November 2024

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tft-stellar#533]

**Comment by ramezsaeed** [comment]
[payouts_signed_by_ramez.txt](https://github.com/user-attachments/files/18063731/payouts_signed_by_ramez.txt)


```
wc -l payouts_to_sign.txt
1171 payouts_to_sign.txt
wc -l payouts_signed_by_ramez.txt
1171 payouts_signed_by_ramez.txt

```

**Comment by mik-tf** [comment]
[payouts_signed_by_mik.txt](https://github.com/user-attachments/files/18063898/payouts_signed_by_mik.txt)

```
wc -l payouts_signed_by_ramez.txt
1171 payouts_signed_by_ramez.txt
wc -l payouts_signed_by_mik.txt
1171 payouts_signed_by_mik.txt
```

**Comment by Nayer-Sobhy** [comment]
[payouts_signed_by_nayer.txt](https://github.com/user-attachments/files/18074969/payouts_signed_by_nayer.txt)

wc -l payouts_signed_by_nayer.txt                    
    1171 payouts_signed_by_nayer.txt

**Comment by delandtj** [comment]
[payouts_signed_by_jan.txt](https://github.com/user-attachments/files/18074990/payouts_signed_by_jan.txt)

```
 ╰─λ wc -l payouts_signed_by_jan.txt payouts_signed_by_nayer.txt
   1171 payouts_signed_by_jan.txt
   1171 payouts_signed_by_nayer.txt
```

**Comment by xmonader** [comment]
[payouts_signed_by_ahmed.txt](https://github.com/user-attachments/files/18075971/payouts_signed_by_ahmed.txt)

```
➜  minting wc -l *
    1171 payouts_signed_by_ahmed.txt
    1171 payouts_signed_by_jan.txt
```
