### ISSUE TITLE
On Stellar mainnet, add asset FreeTFT in a wallet gives a BadRequest

### ISSUE THREAD

**Issue by gmachtel** [threefoldfoundation/tft-stellar#58]
Tested with Lobstr. 
![Lobstr_BadRequest](https://user-images.githubusercontent.com/30384423/78223860-db03e180-74c7-11ea-9699-8aa280033ea2.jpg)

**Comment by robvanmieghem** [comment]
The issuer is activated and the home domain is set but it might be because no tokens have been issued yet.

**Comment by gmachtel** [comment]
Searching on domain name in threefold.io (using Lobstr on mainnet) gives now an error as well (normally both TFT and FreeTFT should appear there). 
![image](https://user-images.githubusercontent.com/30384423/79203441-56a44d80-7e3b-11ea-942e-0f1940cd85cb.png)

**Comment by gmachtel** [comment]
looks ok now, I could add FreeTFT
![IMG_3232](https://user-images.githubusercontent.com/30384423/79235142-853a1c80-7e6b-11ea-84d0-3dbaae3d1ad9.PNG)
![IMG_3231](https://user-images.githubusercontent.com/30384423/79235153-88350d00-7e6b-11ea-8449-629ae5c8d145.PNG)
