### ISSUE TITLE
Trades don't come through anymore in Interstellar testnet 

### ISSUE THREAD

**Issue by gmachtel** [threefoldfoundation/tft-stellar#60]
Trade executed, mentions 'success', but nothing happens afterwards and TFTs don't appear in the account. 

<img width="1278" alt="Schermafbeelding 2020-04-02 om 15 16 38" src="https://user-images.githubusercontent.com/30384423/78253764-2aacd200-74f5-11ea-87b0-998048805d3f.png">

It worked on April 1, not anymore on April 2.

**Comment by zaibon** [comment]
![2020-04-06_800x1131_scrot](https://user-images.githubusercontent.com/303164/78540922-22a2aa00-77f5-11ea-9313-d7c87a3e71cc.png)

Today there is no more offers available at all.

**Comment by VonSub** [comment]
it seems 7th of April a lot of trades went through, but it's down again...

**Comment by VonSub** [comment]
Yesterday evening I succesfully got some trades going.
