### ISSUE TITLE
anonymize the username in the faucet

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#64]
just hash it

**Comment by DylanVerstraete** [comment]
Can't hash that because it is implemented as a callback and the url params are created at the Login page from Jimber

**Comment by DylanVerstraete** [comment]
@robvanmieghem or do you mean anonymizing it in the transaction?

**Comment by robvanmieghem** [comment]
> @robvanmieghem or do you mean anonymizing it in the transaction?

yes, the memo text

**Comment by robvanmieghem** [comment]
8fba0496736b45faea335e8cfc1cc9ca65c9cd5d

**Comment by DylanVerstraete** [comment]
@robvanmieghem can we close this? Since you added this already
