### ISSUE TITLE
how does the oauth work in the faucet?

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#65]
Since I don't see any code in the actor for it, is it all clientside?

**Comment by DylanVerstraete** [comment]
its a client side authentication flow and authenticates at : `https://login.threefold.me`

**Comment by robvanmieghem** [comment]
which means anyone can call the call the actor with any freely chose parameters?

**Comment by DylanVerstraete** [comment]
Yes, but who is going to do that?

**Comment by robvanmieghem** [comment]
Functional requirement in the original issue: "A user can only receive them once for now", Now I can take  as many FreeTFT as I want and block other users from getting their tokens

**Comment by DylanVerstraete** [comment]
@robvanmieghem I have no clue how to secure this actor with the authentication flow from Jimber.

**Comment by robvanmieghem** [comment]
closing this question since it is answered and created a follow up bug: https://github.com/threefoldfoundation/tft-stellar/issues/66

**Comment by robvanmieghem** [comment]
@DylanVerstraete  It's a default oauth 2.0 flow as far as I know
