### ISSUE TITLE
Freetft faucet: no server side session for the threebot login flow

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#66]
currently it is client side and nothing prevents a user from calling the actor with freely chosen parameters

**Comment by DylanVerstraete** [comment]
I have no idea how to do this. Can you please explain on what should be done here?

**Comment by jdelrue** [comment]
We need to update examples for each language (PHP, Python etc) but you can refer to this for the moment:


```python
def is_3bot_user(body_data):
    auth_response = urlopen("https://{}/api/users/{}".format(config.THREE_BOT_CONNECT_URL, body_data['referral_3bot_name']))
    data = json.loads(auth_response.read())
    user_public = data['publicKey']

    verify_key = nacl.signing.VerifyKey(user_public, encoder=nacl.encoding.Base64Encoder)

    try:
        verify_key.verify(base64.b64decode(body_data['signedHash']))
    except:
        return False
    return True

```

**Comment by MathiasDeWeerdt** [comment]
`def is_3bot_user(body_data):
    auth_response = urlopen("https://{}/api/users/{}".format(config.THREE_BOT_CONNECT_URL, body_data['doubleName']))
    data = json.loads(auth_response.read())
    user_public = data['publicKey']

    verify_key = nacl.signing.VerifyKey(user_public, encoder=nacl.encoding.Base64Encoder)

    try:
        verify_key.verify(base64.b64decode(body_data['signedAttempt']))
    except:
        return False
    return True`

**Comment by MathiasDeWeerdt** [comment]
> We need to update examples for each language (PHP, Python etc) but you can refer to this for the moment:
> 
> ```python
> def is_3bot_user(body_data):
>     auth_response = urlopen("https://{}/api/users/{}".format(config.THREE_BOT_CONNECT_URL, body_data['referral_3bot_name']))
>     data = json.loads(auth_response.read())
>     user_public = data['publicKey']
> 
>     verify_key = nacl.signing.VerifyKey(user_public, encoder=nacl.encoding.Base64Encoder)
> 
>     try:
>         verify_key.verify(base64.b64decode(body_data['signedHash']))
>     except:
>         return False
>     return True
> ```
> 
> The fields can just be validated by accessing this API from JS using our example flow.
