### ISSUE TITLE
stellar faucet package: npm build during package install/start

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#68]
Currently this has to be executed manually: https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/stellar-faucet#building-frontend
It should however be executed on package start( or whichever place is best)

**Comment by xmonader** [comment]
in 3bot, nginx will serve `frontend` dir as if it was a single page application. the idea is we compile all deps in the developer machine and ship that compiled/bundled js code along with the package. instead of adding a compilation step and binaries for npm 3bot server.

**Comment by robvanmieghem** [comment]
@xmonader  get, thank you
