### ISSUE TITLE
faucet: after 3bot connect login, I'm sent back to the initial page

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#69]
https://localhost/auth/login?next_url=/threefoldfoundation/stellar_faucet

I accepted the localhost untrusted connection in my browser but the problem remains.
@DylanVerstraete only tested using `nmp run serve`, not through the threebotpackage

How do I run/test this package locally?

**Comment by xmonader** [comment]
is it supposed to have authentication?
if it does, you're required to login with the username you initialized your 3bot with or to be an admin in the 3bot

**Comment by DylanVerstraete** [comment]
@xmonader it does not need authentication for reaching the webserver. Can we disable this login page?

**Comment by xmonader** [comment]
> @xmonader it does not need authentication for reaching the webserver. Can we disable this login page?

If you don't need it you can do `j.tools.threebot.threebotconnect_disable` and you will get into dev mode with no login :)

**Comment by DylanVerstraete** [comment]
![photo_2020-04-05_12-41-06](https://user-images.githubusercontent.com/17138347/78509066-a3c55700-778b-11ea-84d2-df4f2553a07c.jpg)

@xmonader so this screen wont be shown then?

**Comment by DylanVerstraete** [comment]
> > @xmonader it does not need authentication for reaching the webserver. Can we disable this login page?
> 
> If you don't need it you can do `j.tools.threebot.threebotconnect_disable` and you will get into dev mode with no login :)

Where can I add this line? In package.py?

**Comment by xmonader** [comment]
@DylanVerstraete Just do it on the machine and restart your 3bot server :)

**Comment by DylanVerstraete** [comment]
> @DylanVerstraete Just do it on the machine and restart your 3bot server :)

We don't wanna do that on that machine, it has other packages running aswel..

**Comment by robvanmieghem** [comment]
> is it supposed to have authentication?
> if it does, you're required to login with the username you initialized your 3bot with or to be an admin in the 3bot

Yes, I'd like to test this package with the login page in place

**Comment by DylanVerstraete** [comment]
We already implemented a login for the user, no need for the gedis authentication.

**Comment by robvanmieghem** [comment]
on localhost I get redirected to an https version but:
<img width="1279" alt="Screenshot 2020-04-06 at 17 43 28" src="https://user-images.githubusercontent.com/3511318/78577397-4a623400-782e-11ea-88ac-f59fdf0bb5cb.png">

**Comment by waleedhammam** [comment]
If you don't need the location to be authenticated with threebot_connect or the package to be accessible by everyone you can check

in package.py
```
location_obj.is_auth = False 
```

or like admin package to be only accessible by admins: https://github.com/threefoldtech/jumpscaleX_threebot/blob/0b854da520ce8089cc47fc5b657c480bb790e280/ThreeBotPackages/zerobot/admin/package.py#L16

this part is defined in this file https://github.com/threefoldtech/jumpscaleX_core/blob/5814dbb09d654c8c66822e6a0bc8c3a0147278dd/JumpscaleCore/servers/openresty/templates/location.conf#L18

**Comment by DylanVerstraete** [comment]
fixed in: https://github.com/threefoldfoundation/tft-stellar/commit/94eb9f04a25387d83b0034d67e0c9e84f2dd5c4e
