### ISSUE TITLE
faucet: login page improvement

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#70]
Please drop the text "Choose one of the following available methods"
<img width="536" alt="Screenshot 2020-04-05 at 08 20 45" src="https://user-images.githubusercontent.com/3511318/78468268-7094b080-7716-11ea-840c-20e0084624d7.png">

**Comment by DylanVerstraete** [comment]
This page is due to the fact that there is gedis authentication on the packages. We cannot chance the way this page looks in this repository.
