### ISSUE TITLE
Cannot deploy faucet frontend on the threebot

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tft-stellar#78]
For some reason when having set 2 endpoints in the router of a vue app, threebot nginx will not delegate these requests to the right endpoint.

As a (temporary) solution we start the faucet as a node process. In the package.py we created a proxy location to this node process so vue can handle the routing.

To get all things up and running:

Start the threebotserver
```
komos -p
JSX> j.servers.threebot.start()

# add the package
JSX> gedis = j.clients.gedis.get("pm", port=8901, package_name="zerobot.packagemanager")
JSX> gedis.actors.package_manager.package_add(git_url="https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/stellar-faucet", install_kwargs={"domain": "testnet.threefold.io"})
JSX> p.threefoldfoundation.stellar_faucet.start()
```

in another pane
```
# run the faucet app
cd /sandbox/code/github/threefoldfoundation/tft-stellar/ThreeBotPackages/stellar_faucet/faucet_frontend

npm install

npm run serve
```

Now both frontend and actor are running on the same host.

Navigate to the frontend `$THREEBOT_URL/faucet`

The faucet package: https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/stellar-faucet

**Comment by robvanmieghem** [comment]
@DylanVerstraete Can you also document which endpoints and what they return?

**Comment by robvanmieghem** [comment]
and maybe a stupid question but can't handle vue this clientside without having to need a new serverside route?

**Comment by DylanVerstraete** [comment]
@robvanmieghem vue is handling this, these are no serverside routes. It's ngninx not delegating these routes properly to vue

**Comment by robvanmieghem** [comment]
> @robvanmieghem vue is handling this, these are no serverside routes. It's ngninx not delegating these routes properly to vue

that's pretty vague,can you paste such a url?

**Comment by DylanVerstraete** [comment]
maybe this lapis error will show you what is wrong:

```
*10 open() "/sandbox/code/github/threefoldfoundation/tft-stellar/ThreeBotPackages/stellar_faucet/frontend//callback" failed (2: No such file or directory), client: 172.17.0.1, server: , request: "GET /threefoldfoundation/stellar_faucet/callback?signedAttempt=%7B%22signedAttempt%22%3A%22QhNcsl1c8M7qdd%2BdCxbV%2FIXXIzyFEW0ammsFm%2BNx2yfId1hm01wjsnHWn4sN%2BY0jXzL8W89WvMDz%2Fg0nqJXJCHsic2lnbmVkU3RhdGUiOiJCRjBjQm9YQTN2YUNWTkFxUWI5bnJ1ODExOTBrZmdTSCIsImRhdGEiOnsibm9uY2UiOiJuNjJWYzFrbnUrMmpUT1gzckN6dDU5eWlzWjdSZE43bCIsImNpcGhlcnRleHQiOiJuRFY5OXEyUmIxTWRuK2xyT2ZqQU8veU4ifSwic2VsZWN0ZWRJbWFnZUlkIjo4MCwiZG91YmxlTmFtZSI6ImR5bGFudi4zYm90IiwicmFuZG9tUm9vbSI6IjY1ODliYmRjLWQ3MjctNGNmNy1hMTNmLTA0YTY2MDMzZjUyOSJ9%22%2C%22doubleName%22%3A%22dylanv.3bot%22%7D HTTP/1.1", host: "172.17.0.2", referrer: "https://login.threefold.me/login"
```

**Comment by robvanmieghem** [comment]
if it may help: https://router.vuejs.org/guide/essentials/history-mode.html#nginx

**Comment by DylanVerstraete** [comment]
fixed in: https://github.com/threefoldfoundation/tft-stellar/commit/94eb9f04a25387d83b0034d67e0c9e84f2dd5c4e

Changed the vue router to use hash mode and deleted all package.py configuration seems to work.
