### ISSUE TITLE
Better UI for the FreeTFT faucet

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#79]
Currently it looks like
<img width="559" alt="Screenshot 2020-04-07 at 18 22 17" src="https://user-images.githubusercontent.com/3511318/78716050-968ca180-791e-11ea-8c31-9f2fa6dec050.png">

**Comment by DylanVerstraete** [comment]
Define better?

**Comment by VonSub** [comment]
- [ ] Get the ThreeFold Logo in at the top
- [ ] Title: FreeTFT Faucet
- [ ] Textbox underneath so we can provide a little intro to what this does and how to use
- [ ] Use colors / fonts as sent per telegram.

**Comment by DylanVerstraete** [comment]
![Screenshot from 2020-04-08 14-08-35](https://user-images.githubusercontent.com/17138347/78786927-d2b91400-79a9-11ea-9d12-df761326a1f8.png)

**Comment by VonSub** [comment]
Had Zia design a new iteration for the faucet.

![photo_2020-04-10_13-20-02](https://user-images.githubusercontent.com/29431263/78987811-5f410f00-7b2f-11ea-939a-8dde5f65f1ba.jpg)

background and logo can be found in drive:

https://drive.google.com/drive/u/1/folders/1My0n9aSn40VIwo_aXjTBOKECEhX4XaQI

**Comment by gmachtel** [comment]
Still call it ‘faucet’ ? Don’t think that for a production website, this is the right wording. Faucet means a stub, used in test terminology to be able to shortcut part of the code. But here it’s a website where everyone can claim FreeTFTs.

**Comment by gmachtel** [comment]
Call it faucet ? Don’t think it’s right wording for a FreeTFT production process.

**Comment by robvanmieghem** [comment]
indeed, call it "Get FreeTFT's"
