### ISSUE TITLE
hosting the faucet on https://freetftfaucet.testnet.threefold.io does not work

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#87]
Looks like the served html contains absolute paths, for example:`<link rel=icon href=/threefoldfoundation/stellar_faucet/3logo.png>`

**Comment by DylanVerstraete** [comment]
I think the base path should be modified here to just `/`:

- [https://github.com/threefoldfoundation/tft-stellar/blob/2a8e6d3f654dddf89a8929eb93f407c0b4e2a80e/ThreeBotPackages/stellar_faucet/faucet_frontend/src/router.js#L9](https://github.com/threefoldfoundation/tft-stellar/blob/2a8e6d3f654dddf89a8929eb93f407c0b4e2a80e/ThreeBotPackages/stellar_faucet/faucet_frontend/src/router.js#L9)
- [https://github.com/threefoldfoundation/tft-stellar/blob/2a8e6d3f654dddf89a8929eb93f407c0b4e2a80e/ThreeBotPackages/stellar_faucet/faucet_frontend/vue.config.js#L6](https://github.com/threefoldfoundation/tft-stellar/blob/2a8e6d3f654dddf89a8929eb93f407c0b4e2a80e/ThreeBotPackages/stellar_faucet/faucet_frontend/vue.config.js#L6)

and also modify to `/#/callback`:
[https://github.com/threefoldfoundation/tft-stellar/blob/2a8e6d3f654dddf89a8929eb93f407c0b4e2a80e/ThreeBotPackages/stellar_faucet/faucet_frontend/public/config.js#L4](https://github.com/threefoldfoundation/tft-stellar/blob/2a8e6d3f654dddf89a8929eb93f407c0b4e2a80e/ThreeBotPackages/stellar_faucet/faucet_frontend/public/config.js#L4)

All these files in `faucet_frontend` folder should be modified and after you should make another build:
`npm run build`

**Comment by robvanmieghem** [comment]
I don't really get it to be honest, why should all these paths start wit a `/` ?

**Comment by DylanVerstraete** [comment]
Because you are now serving this faucet on / instead of threefoldfoundation/stellar_faucet

**Comment by robvanmieghem** [comment]
Exactly, the absolute paths now have to be modified which would not have been the case if it were relative paths.

**Comment by DylanVerstraete** [comment]
@robvanmieghem we can keep this in mind for later, but can you change the values and try to redeploy?

**Comment by DylanVerstraete** [comment]
added docs in: https://github.com/threefoldfoundation/tft-stellar/commit/64a99ffeadad81898ce679497122f6bf41088bf1
