### ISSUE TITLE
Define TFTA on Stellar testnet and mainnet

### ISSUE THREAD

**Issue by gmachtel** [threefoldfoundation/tft-stellar#93]
TFTA will be the token that TFT on TFchain will be converted in. 
TFTA to be used for 
- payment of capacity (conversion TFTA => TFT on escrow account ?)
- conversion service used by 3Bot Connect app

**Comment by robvanmieghem** [comment]
Will it be used for payment of capacity? Let us first define properly what tfta will be and  align with the stakeholders

**Comment by gmachtel** [comment]
Agree, let's discuss. I understood it will indeed be usable for reserving capacity. And the idea is that a user can already pay with TFTA, but a farmer gets TFT. Conversion can probably happen on the escrow account (where the tokens are residing during the deploy phase), but we need to avoid too many tokens residing on that account (for safety reasons, request @zaibon ).

**Comment by zaibon** [comment]
@gmachtel pretty much said it all.
We need to come up with a reasonable solution to convert the TFTA to TFT.

The important things is we need to ensure the balance TFTA TFT always stays correct so we do not disturb the amount of token that exists.

I also would like to avoid having too much TFT accessible by the explorer. The lesser the better.

**Comment by robvanmieghem** [comment]
Let's put the definition of what tfta is, will be and can be used for in the specs

**Comment by gmachtel** [comment]
Created https://github.com/threefoldfoundation/tft-stellar/blob/master/specs/create_TFTA.md, feel free to complete.
