### ISSUE TITLE
Issue with converting account

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldfoundation/tft-stellar#96]
We tried to convert an account, the service did create the account but the tokens haven't been converted to stellar. The special thing about this transaction is that this contains a lot of transactions.
This is the explorer link to the account: https://testnet.steexp.com/account/GDKW42UJ3VYNXN4INEGGDYRUFGZYDR4ZDFB7BCLLNKMKWBU52IAQFH2C# 
Seed phrase: suggest loyal taxi pluck grab celery solar gentle kitchen link build opinion end cement flight stereo good pluck august lava patch awake stamp retire

**Comment by robvanmieghem** [comment]
Accounts now have to be locked before they can be converted, normally the error ""Tfchain addressess should be deauthorized first before migrating to Stellar!" should have been returned. We need to think of a process to do thid to continue the testing phase.

**Comment by jdelrue** [comment]
This is really critical now, we have need a solution TODAY. Lets meet this afternoon.

**Comment by robvanmieghem** [comment]
@jdelrue As we discussed in the previous meeting we'll add a tfchain address to the ones that can lock accounts, which will not require multisig in this testing phase.
Can you give us an address so we can configure this on testnet?

**Comment by tobiaschielens** [comment]
@robvanmieghem how will this then work in production, will you lock all TFChain addresses at once? We also discussed the idea of a partial release, locking all TFChain addresses is not possible. You can set 010bc4c58fc215f21d9297c4b99b5c86087d60b85304c57db1b0b30e9ee5a6384383dc61247c20 for locking on testnet.

**Comment by robvanmieghem** [comment]
@tobiaschielens part of it is explained here: https://github.com/threefoldfoundation/tft-stellar/blob/master/specs/conversion/locking.md

**Comment by LeeSmet** [comment]
https://explorer.testnet.threefoldtoken.com/explorer/authcoin/condition address added, so you can now lock/unlock accounts

**Comment by tobiaschielens** [comment]
Is there any documentation for the request we have to make?

**Comment by LeeSmet** [comment]
https://github.com/threefoldtech/3bot_wallet/blob/master/authaddress.sh

Replace `goldchainc` with `tfchainc` and the `--auth` flag with `--deauth`

**Comment by tobiaschielens** [comment]
What do I have to setup in order to access tfchainc?

**Comment by jdelrue** [comment]
I will take care of it

**Comment by tobiaschielens** [comment]
Als ik een account lock en dan probeer te converten dan krijg ik volgende error:
![image](https://user-images.githubusercontent.com/17977313/80481074-0f957c80-8952-11ea-8214-02ee57cd8070.png)

Daarna probeerde ik nog eens te converten en het account wordt wel aangemaakt maar de tokens worden niet over gezet.
![image](https://user-images.githubusercontent.com/17977313/80481155-33f15900-8952-11ea-8926-a24fd7452ffa.png)

**Comment by DylanVerstraete** [comment]
Wait until the deauthorization transaction is confirmed by Tfchain before excecuting the migration. We tested this and it solved this issue.
